### ISSUE TITLE
Mixing of CH and LM should be avoided

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1082]
If LM and CH are enabled but LM is not allowed being disabled per request then LMAlgoFactoryDecorator.getDecoratedAlgorithmFactory does not return the defaultFactory even for CH routing requests. This means that we use the currently slower LM+CH combination for this configuration.

**Comment by boldtrn** [comment]
Even worse, this means that if we route between two areas that are separated for LM you cannot route between these areas, even though it should work for CH only.

[I wrote a test, showing the issue.](https://github.com/boldtrn/graphhopper/commit/c20614f25e1e4395a0391bed2aa59b6260e9f87c)

This issue was also reported in the [forum](https://discuss.graphhopper.com/t/can-not-build-route/1998).

**Comment by karussell** [comment]
> I wrote a test, showing the issue

The test does not show the issue I think, because when you allow LM being disabled the decorator works as expected

**Comment by boldtrn** [comment]
> The test does not show the issue I think, because when you allow LM being disabled the decorator works as expected

Ah, yes. You need to remove the lm.disable=true [here](https://github.com/boldtrn/graphhopper/commit/c20614f25e1e4395a0391bed2aa59b6260e9f87c#diff-c2ec919c640e3ecac0c4ed43bcd94935R79). Sorry I should have changed that before committing.

**Comment by karussell** [comment]
> Sorry I should have changed that before committing.

I meant with `put("routing.lm.disabling_allowed", true)` the issue does not occur for the default case.

**Comment by karussell** [comment]
Fixed and deployed

**Comment by IldarKhayrutdinov** [comment]
it seems that there is still some problem, Moscow -> Berlin builds via CH, but with a custom profile (via LM?), even with an empty, doesn't build

https://graphhopper.com/maps/?point=moscow&point=berlin&profile=car

![image](https://user-images.githubusercontent.com/29858598/123911732-d35e1180-d984-11eb-9e23-4052df260ec8.png)

**Comment by easbar** [comment]
Yes for LM we do not get a connection here probably because of the landmark splitting, @karussell?

**Comment by karussell** [comment]
Yes

**Comment by IldarKhayrutdinov** [comment]
I don't know much about graphhopper terminology, what does mean landmark splitting? Is it possible to fix the problem what would work LM Moscow to Berlin?

**Comment by easbar** [comment]
The landmark algorithm splits the world map into disconnected regions. For example this is no problem for Europe/America because these continents are not connected anyway (GraphHopper does not consider airplanes or trans-atlantic ferry trips). But for Eurasia there is an artificial border which happens to be between Berlin and Moscow. Unfortunately the only workaround is using AStar at the moment, so you need to set `disable.lm=true`.

**Comment by IldarKhayrutdinov** [comment]
Thanks for the clarification, now I get it. Where can you find an artificial border, where are they described?

**Comment by IldarKhayrutdinov** [comment]
thanks very much!
