### ISSUE TITLE
Rename PathWrapper

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1147]
I think the data types of the request and the response should be named concisely for what they are.
PathWrapper doesn't wrap a path, it _is_ a path.

Except if we think it is a route, because we always say we calculate routes, not paths.

**Comment by karussell** [comment]
You mean a route is a list of paths?

**Comment by michaz** [comment]
No, what makes you think that? A PathWrapper is also not a list of paths. I think a path and a route are the same.

**Comment by karussell** [comment]
What is the difference of a path and a route in your opinion? Or why do you think: "Except if we think it is a route..."

**Comment by michaz** [comment]
I meant: Maybe we should rename it to Route, not to Path, because Route is the word we are using everywhere else. But _at least_ to Path.

**Comment by karussell** [comment]
There is already a Path class and I think the problem is probably that the PathWrapper class is also like a data transfer object that can and should be avoided somehow.

**Comment by michaz** [comment]
But if PathWrapper is a data transfer object (it is!), that specifically means it _doesn't_ wrap anything.

**Comment by karussell** [comment]
Sure. What is your suggestion to call it?

**Comment by michaz** [comment]
Wait until after the client+dropwizard PRs, because then would be a good time to move all the API data transfer objects to their own package. Then we see them all together in one place, and can decide on the perfect data type names? :-)

**Comment by karussell** [comment]
Now it could be time to resurrect this ;)

**Comment by easbar** [comment]
I agree that `PathWrapper` is misleading because it does not wrap a `Path`. `Path` is the the temporary thing we use during calculations, `PathWrapper` is the thing contained in the `GHResponse`. Maybe call it `CalculatedRoute` ? `RouteResponse` ? `ResponsePath` ? `Route` ? `RouteDTO` ? `PathDTO` ?

I think I would prefer `ResponsePath`. Using `Route` in any combination might lead to more confusion (whats the difference between a route and a path...) and so far `Path` is used in most classes (`PathDetails/Merger/Simplification...`)
