### ISSUE TITLE
Bicycle routing not passing turning cycle

### ISSUE THREAD

**Issue by kaipankrath** [graphhopper/graphhopper#1152]
This https://graphhopper.com/maps/?point=47.563905%2C7.601375&point=47.564188%2C7.60219&locale=de&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale (pedestrian) does return the correct result, but this https://graphhopper.com/maps/?point=47.563905%2C7.601375&point=47.564188%2C7.60219&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale (bike) does not. I looked at the raw data https://www.openstreetmap.org/#map=18/47.563928/7.601315 and see clearly that the truning cycle could be a problem, but the traffic restriction contains the attribute “bicycle=yes” (I added that a few days ago) - this should work.

**Comment by boldtrn** [comment]
IMHO, the issue is that this [way](https://www.openstreetmap.org/way/436446189) has `vehicle=private`. BTW: I think GraphHopper does not even consider the type `turning_circle`, which also seems no issue, since this is supposed to be mapped to nodes.

[Here is a route using a turning_circle](https://graphhopper.com/maps/?point=51.20348%2C3.24733&point=51.20334%2C3.24709&vehicle=bike&weighting=fastest)

**Comment by karussell** [comment]
Hmmh, strange. Why does it work for foot then as we have `restrictedValues.add("private");`?

**Comment by boldtrn** [comment]
> Hmmh, strange. Why does it work for foot then as we have restrictedValues.add("private");?

I would say, because it is [vehicle=private](https://github.com/graphhopper/graphhopper/blob/1f97e5c0b6537c2f15e8c302a542c2e1316299d4/core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java#L70) and not access=private. [Foot does not care about vehicle](https://github.com/graphhopper/graphhopper/blob/1f97e5c0b6537c2f15e8c302a542c2e1316299d4/core/src/main/java/com/graphhopper/routing/util/FootFlagEncoder.java#L73).

**Comment by karussell** [comment]
Ah, makes sense. @kaipankrath does it make sense to you too :) ?

**Comment by kaipankrath** [comment]
Actually it does - now I can take that discussion to the guy I am working with on that area. Most probably I need to review the signature on site and check the attributes on the street. However I get the argument.

**Comment by ratrun** [comment]
If you look at the data and on the calculated route you see that you get routed along the edge of the "Messeplatz", which currently is tagged as highway and area=yes. There is no edge between this "Messeplatz" area and the turning circle.

**Comment by kaipankrath** [comment]
Finally we solved that in OSM adding an attribute to a small part of the street, see https://www.openstreetmap.org/note/664769 for details (in German). Now the bike routing works as expected.

**Comment by karussell** [comment]
Thanks for the update!
