### ISSUE TITLE
algorithm=round_trip does not work in GH Maps

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1218]
The routing request is not triggered. Probably because there is just one `point` parameter

**Comment by carlos-mg89** [comment]
I'm trying to figure out how to use the `round_trip` algorithm. I haven't really found any documentation in the Routing API docs https://graphhopper.com/api/1/docs/routing/

I have received an error message saying:

> "Round trips must have exactly 1 point"

It doesn't make much sense to me that the `round_trip` algorithm only works when 1 point is on the 'route'. It only makes sense to me when there are at least 2 points, so for example, I can calculate how to go from point A to point B, and then, without adding anything else than the `round_trip` algorithm, it will automatically calculate how to go back to point A.

Perhaps what this bug is saying is that the `round_trip` algorithm doesn't work at all at the moment?

**Comment by karussell** [comment]
No, it works (see the tests) but the demo UI currently is too restrictive and cannot show it.

> It doesn't make much sense to me that the round_trip algorithm only works when 1 point is on the 'route'.

A round_trip is defined using one point, the distance and an optional heading. I do not see how 2 points could make sense for a round_trip.

**Comment by ammagamma** [comment]
I think carlos-mg89 thinks of a round trip as going from A to B and back to B again. The round_trip algorithm in GH uses some heuristic/parameters (described in `api-doc.md`) to automatically calculate a roundtrip of given length, heading etc. back to a given starting point.

**Comment by carlos-mg89** [comment]
Ohhh! Now I understand what you meant by `round_trip`. I was thinking it'll calculate the way back, given a set of waypoints (route stops).

Then it isn't what I was looking for. I'll simply add the same waypoints to the request to calculate the way back.

Thank you, and sorry for writing something that has nothing to do with this algorithm.

Yeah, that's what I thought for a round trip @ammagamma :)
