### ISSUE TITLE
Web demo UI should use u_turn.png instead of u_turn_unknown.png

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1251]
We should not need two different icons here IMO

**Comment by boldtrn** [comment]
The idea was to have 3 different icons.

One for a left u-turn, one for a right u-turn, and one for a u-turn without defined direction. We can just show one icon if you want?

**Comment by karussell** [comment]
>  and one for a u-turn without defined direction

Yes, but this one should be named just u_turn.png IMO

**Comment by karussell** [comment]
But if you think it is important and/or fast to do, then of course every focus distraction is nice :)

**Comment by boldtrn** [comment]
> Yes, but this one should be named just u_turn.png IMO

Ok sure, I just thought since we add a direction _left and _right, it would make sense to make clear that in this case the direction is unknown or unspecified. I can rename it either to u_turn.png or u_turn_unspecified.png. We could also rename the unknown case to "turn around", in this case we just ask the user to turn without providing any directions, so it might be the best to enter a side road and turn there, continue to the next roundabout, etc. and not necessarily perform a u-turn or a 3 point turn. 

 > But if you think it is important and/or fast to do, then of course every focus distraction is nice :)

What do you mean here?
