### ISSUE TITLE
Missing turn instructions where improvement already expected

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1252]
With the improved instructions I would have expected instructions at the red circles in [this route](https://graphhopper.com/maps/?point=42.507034%2C1.531906&point=42.509581%2C1.532421&layer=OpenStreetMap) in Andorra:

 1. left
 2. right
 3. keep right

![missing-instructions](https://user-images.githubusercontent.com/129644/34416877-e382327e-ebf5-11e7-999c-300be3398f6b.png)

Maybe related to #1048 or only partially fixable or even not fixable at all without further road information (that will be added with #1112). If so, please close for now.

**Comment by devemux86** [comment]
> Maybe related to #1048

I think that's the case, i.e. skip instructions if the turn is the only valid way.
Though to perform that check, should already know all node exits validity?

**Comment by boldtrn** [comment]
Yes 1 and 2 are due to #1048. I have seen many more cases like this and I think we should fix this issue soon. On the other hand, this will create some irritating instructions as well, like when entering the highway, it might prompt the user to turn slightly right. Having the road data would be good and might help to prevent many of these unnecessary turn instructions.

**Comment by karussell** [comment]
ok, regarding focus: we should start #1112 now (and make #1108 even earlier :))

> GraphHopper shows a "Continue onto Avinguda Consell d'Europa", which IMHO is the correct instruction. 

:+1:

**Comment by boldtrn** [comment]
> ok, regarding focus: we should start #1112 now (and make #1108 even earlier :))

Ok, I thought so :). I will close here and add you example to #1048.
