### ISSUE TITLE
Routing fails with hint pass_through and via points near dead-end ways or junctions

### ISSUE THREAD

**Issue by NopMap** [graphhopper/graphhopper#1258]
Graphhopper Version: 0.9 stable branch
JVM: Oracle x64 1.8
OS: Windows7 x64
Reproducible: Always

How to reproduce:
- set hint pass_through
- use 3 points for routing
- place the via point behind a dead-end way so it is snapped to the end point tower node of the way (see picture 1)

=> routing fails

Additional findings:
- when **pass_through** is de-activated the exact same point works.
- when the snapped point is **on** the dead end way, but not the end point, the routing works (see picture 2)

[Picture 1](https://discuss.graphhopper.com/uploads/default/original/1X/b5918e80a0f9e2beeb18c13571e4abccb06f35b2.png): via point is snapped to end point tower node, routing fails

[Picture 2](https://discuss.graphhopper.com/uploads/default/original/1X/7e34fd995faaff9d2ff1ebf745ed86289176ac88.png): via point is snapped to a point on the way, routing works

[Associated forum discussion](https://discuss.graphhopper.com/t/questions-on-migration-from-gh-0-1-to-0-9/2695/25)

**Comment by karussell** [comment]
Thanks! Can reproduce it also on the current deployed version: https://graphhopper.com/maps/?point=51.451403%2C14.26778&point=51.450564%2C14.265726&point=51.450263%2C14.268236&ch.disable=true&pass_through=true

**Comment by boldtrn** [comment]
I had a closer look what is happening here.

When we match a point close to a dead-end, we will match it as `Position.TOWER` in the LocationIndex. We don't create `VirtualNodes` for [TOWER QueryResults](https://github.com/graphhopper/graphhopper/blob/91ca93d8520480f3d103a79962ecabad35f72c78/core/src/main/java/com/graphhopper/routing/QueryGraph.java#L226).

Fixing this seems not straight forward. We keep an unfavored flag for VirtualEdges in memory. Storing this for every edge might be too much?

Other possible but not optimal fixes could be:
- Pass a list of EdgeIds to the weighting that contains unfavored edges, instead of storing the unfavored information in the edge. This might actually be slower than our current approach.
- Create a VirtualEdge for TOWER nodes as well. I don't think that this makes sense to be honest :).
- Don't throw an exception in `QueryGraph#unfavorVirtualEdgePair`, but just "fail" silently. The same happens already in `QueryGraph#enforceHeading`, where we just don't do anything if it's not a 
`VirtualNode`.

I think I would go with the "don't throw and exception" solution. It's a corner case and we should create an issue for how to handle edge unfavoring for non VirtualEdges. This can happen both for the heading as well as the pass through parameter.

**Comment by easbar** [comment]
We have the same problem if a via point sits directly on a junction:

https://graphhopper.com/maps/?point=48.692337%2C9.118767&point=48.692013%2C9.122549&point=48.692363%2C9.129286&locale=en-US&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale&pass_through=true&ch.disable=true

Taken from this forum discussion: https://discuss.graphhopper.com/t/node-id-must-be-a-virtual-node/4829/3

**Comment by michaz** [comment]
Wouldn't the most general solution to this be that locations can't be on "real tower nodes", but _only_ on links? Like, just remove the special case where a point is snapped to a node instead of a link?

People don't live on intersections, they live on road addresses. Every routable location should be on a road, not on an intersection.

**Comment by michaz** [comment]
Or put differently: Mathematically, the probability of a random point on a graph embedding falling on a node is 0. So we only _create_ the special case by snapping it.

**Comment by michaz** [comment]
(My argument doesn't work that well for the dead-end case.)

**Comment by easbar** [comment]
> People don't live on intersections, they live at street addresses. Every routable location should be on a road, not on an intersection.

I think I agree and maybe we can get rid of some complexity if we can always assume that a `QueryResult` sits on a virtual node *between* tower nodes (basically always have `Position.EDGE`). But of course this solution just moves the problem to the location index lookup: we have to make sure that we always snap somewhere next to the node for cases where we snapped onto a node before (I think this applies for junctions just like it does for dead-ends). For junctions we even have to make a decision onto which of the adjacent edges we want to snap.

The thing that strikes me more here though is that for `pass_through` snapping onto a real node (a junction or dead end) is a special case (that we do not handle at the moment), but this is only because of the way the feature is implemented. There is no real problem with this and it is clear what should happen also in this case. All we want is not take a u-turn at the via points so we start the next leg with an edge that was *not* the one we used to arrive at the via point. Ok for dead ends this is indeed problematic and we have to allow the u-turn in this case (because there is no other alternative). But for junctions (in principle) this is not a problem at all.

**Comment by naser13** [comment]
> I think just quitely ignoring it instead of failing the routing should be enough.

i think this approach is at least better than failing.
similar to how it's done in `QueryGraph.enforceHeading`:
`        
if (!isVirtualNode(nodeId))
            return false;
`

**Comment by NoamDev** [comment]
What about creating a virtual node "just before" the tower node (with weighting 0)?
Then, the problem for junctions will be solved.

Another idea, is to use edge based routing, this way pass_through will work on junctions, dead-ends.
This will also enable using pass_through in speed mode (#1765).

**Comment by NoamDev** [comment]
The problem wih dead-ends can be solved with edge-based routing, as I suggested in (#1765).

**Comment by NopMap** [comment]
After reading through these comments and the linked issues, I am still not clear whether the issue with the U-turn routing fails here was solved somewhere there in the meantime and whether it is save now to use the pass_through parameter.

Can you enlighten me, please?

**Comment by easbar** [comment]
Yes, it is safe to use.

* pass_through + CH is forbidden and you'll get an error telling you that pass_through + CH is not supported
* pass_through will be ignored silently at dead-ends and junctions (since dc2bbd5e3798987a625bd3dbf56f52f13a680c26)
