### ISSUE TITLE
Broken graph after removing subnetworks, then adding nodes

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1313]
Adding edges (or, at least, adding edges to new nodes) to a graph after having removed disconnected subnetworks results in a corrupted graph:

https://github.com/graphhopper/graphhopper/commit/7f82541a3d391d53d7992df3333e48cb6d0a7a4a

**Comment by karussell** [comment]
This is ugly - thanks for finding and already writing the failing test :) :+1: !

We currently remove the nodes in the graph and do the compaction in-place to avoid holding two (potentially really big graphs) in memory. But we do this only for the nodes and leave the invalid edges in the graph. Maybe we should do the same for the nodes and create an optional but much simpler graph copying mechanism as this in-place compaction made lot's of problems and changes the node-IDs and potentially does not save so much RAM that the problems are justified.

**Comment by michaz** [comment]
Yes, I must admit I had a moment of panic where I was afraid that we would be changing the edge ids. (I hold on to them and save them and do lookups on them!) But luckily we aren't.

**Comment by karussell** [comment]
I think the problem is that we do not reset the pointers to the edges of the invalidated nodes in the graph.optimize() call. So in the test the edge 7-8 is created and 8 is still linking to some old edges and we append now 7-8 to the linked list and reanimate an edge with invalid nodes.

The fix is here: https://github.com/graphhopper/graphhopper/commit/6be91f3131d5c54a8476bc7dbd88c99b98914dbf

**Comment by karussell** [comment]
Strange, this does not make sense because we call baseGraph.trimToSize();

**Comment by karussell** [comment]
Ah, we keep only the necessary [but complete segment files](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/RAMDataAccess.java#L297)
