### ISSUE TITLE
Find some better way to handle parameters for algorithm preparation

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1368]
Graph preparation like CH and LM typically depends on some kind of parameters like the number of lazy updates in CH or the number of landmarks in LM. As of now these parameters are set via setters or the constructor in the corresponding preparation classes and the number of parameters is relatively small. For CH with turn costs (and possibly other future algorithms) there will be a few more parameters that are also needed in different places and while there should always be some good default values there should still be a way to adjust the parameters to special situations, hardware etc. Especially when the preparation classes are split into multiple (like PrepareContractionHierarchies and NodeContractor) we need to pass the parameters down from one class to the other (for example from `CHAlgoFactoryDecorator` to `PrepareContractionHierarchies` to `NodeContractor` etc.). This is rather cumbersome and adding/changing/removing a parameter requires changing multiple classes. I think it would be cleaner to pass along a `PMap` options object (that is where the parameters originate from anyway) such that each related class can pick the options that it requires. This might sound a bit like some kind of global object and obviously should not be misused to hold some other state, but I think as long as it is solely used as a read-only parameter object this is totally fine and makes the code easier to adjust to future changes. What do you think ?

**Comment by ammagamma** [comment]
> But when we put everything into a ConfigObject, we still need to change each class if we change a parameter?

This depends on the amount of code that is required to pass along the config object and the amount of code that is used to write/read from the object. As soon as the config object is passed down the chain of classes that need it adding a parameter is only a matter of adding it initally and using it wherever it is needed, while adding a single parameter requires adjusting all the setters used in the chain.

> The problem with maps is that you can change a key at one end but forget to change it at the other end. You would only find this once the code crashes.

Yes, we lose the safety provided by the type system, but since the config fields are only used to override the (hard-coded) default values nothing would crash, but it might happen that a misspelled key leads to some parameter not being overwritten (which you might argue is even worse ;). At the same time I think this is also an advantage we have less compatibility issues. I remember this was the reason why we used a simple String instead of a static constant in a similar situation here:
https://github.com/graphhopper/graphhopper/blob/06ef11047737cb86c6c81090dedf7d986055dc94/core/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java#L197

One problem I am seeing with a dedicated java class as configuration object is that we need some notion of "parameter not given -> use the default". We could use null values to indicate this, but without using something like java 8 `Optional<T>` or at least some kind of copy of it, it will be a bit ugly to read the values while `PMap` already provides a getter that takes a default value that is returned when a key is missing.

> I would be all for it? 

Ok, good :) I think both using a java config class and using a PMap is better than providing single setters for each parameter.

> But then we would probably need different configurations for CH and LM?

Well, this depends on how strongly we want to separate unrelated parameters from each other and depending on this we might even need multiple configuration objects for CH (node/edge based etc.), but for now I think it would be easiest to group some related parameters together and later see if we want to merge more of these objects into one ? An extreme case would be having one config class for everything, basically a java side representation of the config file, but I do not think this would be a very good idea. Here I think again that a PMap is a better solution (at least on the high level classes, which we more or less do at the moment), because it does not require us to even make this decision.

**Comment by karussell** [comment]
> The problem with maps is that you can change a key at one end but forget to change it at the other end. 

For the CH preparation it usually is just one place: where you read the value. And setting the value is done via command line arguments e.g. to run the algorithm with different configs. And for me the normal user will never ever touch these values and so nothing is broken as we provide meaningful defaults that can be easily updated.

> At the same time I think this is also an advantage we have less compatibility issues. I remember this was the reason why we used a simple String instead of a static constant in a similar situation here:

:+1: 

> Ok, good :) I think both using a java config class and using a PMap is better than providing single setters for each parameter

:+1: 

I can live with both ... just some further pro/con thoughts:

PMap will be less code and it is easier to try out new parameters.

One big advantage for a Java object is its type safety and better readability and highly likely that we can directly read it from the yml file. But I think it should be easy to store defaults in the Java object instead of null so no real disadvantage.

**Comment by ammagamma** [comment]
> it should be easy to store defaults in the Java object instead of null so no real disadvantage

I'm not so sure about this, for example the 'default value' of `minimumNodes` in `LandmarkStorage` is not a simple number but depends on the number of nodes in the graph: https://github.com/graphhopper/graphhopper/blob/06ef11047737cb86c6c81090dedf7d986055dc94/core/src/main/java/com/graphhopper/routing/lm/LandmarkStorage.java#L89

**Comment by karussell** [comment]
> I'm not so sure about this, for example the 'default value' of minimumNodes in LandmarkStorage is not a simple number but depends on the number of nodes in the graph

But this could become something like:

this.minimumNodes = Math.min(graph.getNodes() / 2, config.getInitMinimumNodes()); 

Or maybe the dynamic nature is not necessary anymore with the config object.

**Comment by ammagamma** [comment]
Ok, yes there should be some way around this usually. In this example the 'real' parameter is 500_000 and the problem is rather that the max limit of graph.getNodes() is not enforced in the setter of minimumNodes. ? Regarding the 'its easier to quickly try something with maps' argument I usually just use public static constants for quick experiments, so I do not see a real advantage here.

**Comment by boldtrn** [comment]
> One big advantage for a Java object is its type safety and better readability and highly likely that we can directly read it from the yml file. But I think it should be easy to store defaults in the Java object instead of null so no real disadvantage.

Isn't it possible to specify defaults for the deserialization? Like if value is not present set it to 5. The same could continue to work as we do it right now like:

`Object.setStallOnDemand(args.getBool("stall_on_demand", true))`

This could be improved by having a Builder that creates final properties (if needed).

> And for me the normal user will never ever touch these values and so nothing is broken as we provide meaningful defaults that can be easily updated.

Good point as well.

> this.minimumNodes = Math.min(graph.getNodes() / 2, config.getInitMinimumNodes());

Yes this would be indeed better. I think if possible, the config object/map should be as simple as possible to not mix with any business logic.

**Comment by karussell** [comment]
> Regarding the 'its easier to quickly try something with maps' argument I usually just use public static constants for quick experiments, so I do not see a real advantage here

For an automated comparison for many different combinations I needed them to be available as command line arguments

**Comment by ammagamma** [comment]
> I needed them to be available as command line arguments

Yes, me too. I took the parameters from the config arguments and used them to set the global constants, which at least saved me from passing them down to where I needed them.

**Comment by easbar** [comment]
Went with the pMap approach in the CH preparation related code.
