### ISSUE TITLE
Strange routing via ferry

### ISSUE THREAD

**Issue by jguthrie100** [graphhopper/graphhopper#1382]
If you get directions from Leeds, UK to Dublin, Ireland, then you get three different routes based on whether you select foot, bicycle or car routing.

But the strange thing is that they are wildly different, taking three completely different ferry journeys at the added expense of 100s of km!

[by bike](https://graphhopper.com/maps/?point=Leeds%2C%20United%20Kingdom&point=Dublin%2C%20Ireland&locale=en-GB&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

[by foot](https://graphhopper.com/maps/?point=Leeds%2C%20United%20Kingdom&point=Dublin%2C%20Ireland&locale=en-GB&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

[by car](https://graphhopper.com/maps/?point=Leeds%2C%20United%20Kingdom&point=Dublin%2C%20Ireland&locale=en-GB&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

There's a clearly more direct ferry which is surely applicable for all modes of transport??

**Comment by karussell** [comment]
Interesting, thanks. 

There are multiple issues involved (I just investigated a little). One issue seems to be that one ferry is not publicly connected to the mainland i.e. [this way is private](https://www.openstreetmap.org/way/26579083#map=19/53.31403/-4.62412) (same for the other terminals)

And [this ferry](https://www.openstreetmap.org/way/54049736) only allows foot and car so obviously bike avoids it.

And the same ferry is not used for car highly likely because the duration is very long (8h) compared to the [used one](https://www.openstreetmap.org/way/44643127) (3.5h) accepting a huge detour on the mainland.

**Comment by karussell** [comment]
The routes for foot and car are now reasonable. For bike the ferry still does not include access so I'll close this here.
