### ISSUE TITLE
Isochrones in the water

### ISSUE THREAD

**Issue by araichev** [graphhopper/graphhopper#1393]
Hi folks, testing the [Graphhopper isochrone web service](https://graphhopper.com/api/1/docs/isochrone/), i get polygons containing the sea.
For example, querying the isochrone API with the lon-lat point [174.76725965738297, -36.84730262945269], the time limit of 30 minutes, and the vehicle 'bike', i get the polygon pictured in the attached image.
I didn't expect to be able to ride my bike into the harbor.

![auckland_bike_isochrone](https://user-images.githubusercontent.com/4087432/41389160-5bf3d872-6fe3-11e8-9e00-02aa10c3af46.jpg)

**Comment by karussell** [comment]
There are certainly suboptimalities with our isochrone service (like including roads that are not reachable), but including sea is none of them IMO. Because you can assume to travel on roads only, excluding also many of the area of the "mainland" too like private or farming area. Furthermore assume you would exclude water from the polygon then we would be forced to return a very precise polygon without the possibility for simplification. So the definition of our polygons should be "includes reachable roads only"

**Comment by araichev** [comment]
Fair enough.
