### ISSUE TITLE
Isochrones for public transit

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#1421]
Like this:

http://localhost:5000/isochrone?point=45.5176544,-122.6781463&pt.earliest_departure_time=2018-07-03T18:43:04Z&time_limit=1200

<img width="758" alt="screen shot 2018-07-03 at 16 18 57" src="https://user-images.githubusercontent.com/520916/42225647-524eb54a-7edd-11e8-9a58-6bc462407d20.png">

**Comment by michaz** [comment]
Happening here:

https://github.com/graphhopper/graphhopper/tree/pt-isochrones

**Comment by michaz** [comment]
Note how intermodal isochrones look totally different from walk-only or car-only ones.

First, you get islands, and they are not artifacts, but part of the story.  I can get to a far-away place, but I can't leave the bus in between.

Second, you get these cute ice-cream-cone-shaped things around lines, where towards the end of the time-budget, the time you have left to spend walking away from the bus stop gets smaller.

**Comment by karussell** [comment]
Beautiful :)

**Comment by culebron** [comment]
I used to do such isochrones with 2GIS or Google PT, but that was paid service, hence low res. In the end I made a hybrid router: routes to stations via PT router, then OSRM foot isochrone. But that was still expensive and error-prone (many unexpected bugs coming out at you).

I did a similar research in Moscow, where isochrones are spindle-shaped. In 30 minutes the subway catapults you in the center, but you can't reach the neighbor subway line.

![image](https://user-images.githubusercontent.com/119675/42291521-66bee7e2-7ff6-11e8-96f0-b7c83865aadc.png)

My city with 2GIS router:
![selection_010](https://user-images.githubusercontent.com/119675/42291466-019db30c-7ff6-11e8-8aa8-97b9600fac03.png)

**Comment by michaz** [comment]
@culebron Wow.

**Comment by michaz** [comment]
I think some kind of model-based smoothing would be nice. Look at all the little holes, where you can "just barely" not go within the budget. Those are _real_, but probably not _significant_, since travel time should come with an error bar anyway, and the entire hole surely lies within it.

**Comment by michaz** [comment]
I'll let it sit for a while, since I want some theory before I just say "fill holes smaller than X".

Meaning I'm looking for a better reason than "too complex" (for what?). :-)

**Comment by karussell** [comment]
> Meaning I'm looking for a better reason than "too complex" (for what?). :-)

haha, sure :+1: 

Highly likely this must be configurable (than you also avoid thinking about it ;)): because a database request needs a simple polygon to make the SQL request fast but for a visualization you could show a arbitrarily complex polygon and probably there are many use cases in between.

**Comment by michaz** [comment]
> where no streets are

Yeeeeah, that's problem 2. And it's totally not clear to me yet. When dealing with networks, the only "isochrones" where it's totally clear (to me) what they mean are yours, where you just draw links which are reachable and don't draw links which are not. And you don't know anything about non-links. But even there, you have problem 1: If one link _in the middle_ is not reachable while all the others around it are, do you remove it or not?

**Comment by michaz** [comment]
Problem 2: How do you operationalize what a firefighter or city planner means when they say "draw me lines around the area which my engines can reach in 8 minutes / people can reach by transit within 20 minutes".

**Comment by karussell** [comment]
If we use a grid (independent of the road-network) both problems get simpler (I think, but not 100% sure :)):

we just fill a cell of the grid if it contains a reachable point and it stays empty if not and an isochrone polygon then describes the filled area. But for visualization this does not look that good, I fear. Even for high resolution. And for the database request the polygon at the border of this area might be still "too complex". Hmmh.

**Comment by michaz** [comment]
> If we use a grid

Yeah, I found that solution implemented, too. It's nice, and it makes sense, but it seems to move the responsibility into the grid cell size parameter, which you just tweak until it looks the way you want it to look. Hmpf.

**Comment by culebron** [comment]
@michaz at my work, we had discussions on smoothing, and I think there's no sane solution to this. I ended just cutting holes away, because in many places they were faults of routing rather than be in physical world.


Grid has its own problems as well. It creates islands of its own, even with foot or car isochrones, which unilke PT should be continuous. 

With grid a straight road that goes diagonally (NE, NW, SE, SW) generates such islands. I tried curing it by adding nodes on the highway, which in turn causes more islands because on the other side of 2-way road nodes have much higher duration. See the example: most points fall on the wrong side of the road, and drive time is 10 minutes bigger (you need to make a U turn far away). But one point hits the right side, and gets much smaller drive time (24 minutes rather than 30+).

![photo_2018-07-06_01-08-29](https://user-images.githubusercontent.com/119675/42340147-76ed2354-80b9-11e8-8513-8301769ab02f.jpg)

Another example:

![photo_2018-07-06_01-16-05](https://user-images.githubusercontent.com/119675/42340443-37ef8d3a-80ba-11e8-96e8-2b61908f50f7.jpg)

Smoothing does not connect islands, quite opposite, it cuts some peninsulas off. See the non-smoothed isochrone and a smoothed one: there are still some quite big islands.

![photo_2018-07-06_01-05-19](https://user-images.githubusercontent.com/119675/42340183-8ee535b4-80b9-11e8-826f-e4dbb50b3183.jpg)

Smooth surface creates it's own artifacts, I had to abandon this idea completely. In the next picture, you see it tries to continue the gradient (26=>16) to where it does not exist, producing pixels with values much less than 16.

![photo_2018-07-06_01-00-49](https://user-images.githubusercontent.com/119675/42340326-edc52e9a-80b9-11e8-9b39-59c9d899a0b7.jpg)

And a larger view with edge artifacts. Any very different value causes "waves" and insane level curves.

![photo_2018-07-06_01-16-08](https://user-images.githubusercontent.com/119675/42340467-493667da-80ba-11e8-9dd7-379c1d3a74c8.jpg)

We had a sort of "parallel red and green lines in a shape of cat" discussion there. Colleagues suggested ways to connect diagonally situated grid nodes, but in the end there's no easy algorithmic way. Again, the first picture with 24 minutes point faaaar away, won't be fixed this way.

![photo_2018-07-06_01-08-02](https://user-images.githubusercontent.com/119675/42340249-b7d153b8-80b9-11e8-8a73-be6cda0e3832.jpg)

Since client managers wanted pretty pictures, we just cut off islands smaller than 1/3 of the biggest polygon (yep, arbitrary beauty). You might try hexagonal grid, it does look prettier, but I suspect it still has some artifacts.

![photo_2018-07-06_01-00-22](https://user-images.githubusercontent.com/119675/42340266-c2d66c08-80b9-11e8-9320-1f85ed2d1a36.jpg)

Walking over a graph is more sane, at least Graphhopper produces the best isochrones I've seen. If it can be accelerated a bit, it would be perfect. Right now they are notably slower than OSRM grid + matplotlib, and for instance, in my work, we made about 10K-20K at a time (car/foot/car with traffic for 5,10,15,20,30 minutes, for 100-500 points at a time).

## Options

I'd ask for one important option: if we build isochrones for like 10,20,30 minutes, they should be available in 2 ways. One is when 20-minute multipolygons include those for 10 minutes. The other way is have holes.

That's because sometimes you need to count all objects that are reachable in 20 minutes, sometimes you need only those between 10 and 20. In python, I just collected the outer circles of 10-min polys and added them as holes to the 20-min ones.

**Comment by michaz** [comment]
+10 for putting this together, and for reinforcing my hunch that doing this graph-based is the way to go. 

My re-confirmed current plan is now to let this sit until I have a big block of uninterrupted time, and then re-implement this using CGAL, which will let me get constrained triangulations (so that roads stay roads) in sensible computation time, and then.. let's see.

Thanks again!

**Comment by culebron** [comment]
Finally managed to assemble graphhopper to test this branch. When I make a request, it resets connection, but java server continues calculating something, using CPU a lot.

**Comment by karussell** [comment]
Fixed via #1480

**Comment by kasper747** [comment]
> Finally managed to assemble graphhopper to test this branch. When I make a request, it resets connection, but java server continues calculating something, using CPU a lot.
> 
> What is memory usage for GTFS? Berlin GTFS worked normally on a laptop with 10GB RAM, but strangely Saint Petersburg GTFS did not, I had difficulties building it.

For Brandenburg I needed 16GM. It takes a lot of memory when building. Therefore I build it on a virtual server.
