### ISSUE TITLE
remove deprecated ISO8601DateFormat

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1457]
[It looks](https://github.com/FasterXML/jackson-databind/issues/1786) we can remove the call

bootstrap.getObjectMapper().setDateFormat(new ISO8601DateFormat());

as this is recommended according the linked issue and all tests are still green.

**Comment by michaz** [comment]
..which shows I am missing client tests for the `Leg` type, because removing this does something totally different, and putting in `StdDateFormat` does something _a little_ different.

Good thing is, Janek's client doesn't care and correctly parses whatever it gets, so I'll just put in `StdDateFormat` for now, since what that does _is_ actually ISO-8601 compliant, just a slightly different interpretation of it.

**Comment by karussell** [comment]
> Janek's client doesn't care and correctly parses whatever it gets,

But could this break other clients? If yes, we should either postpone or explicitely document it somewhere.

> which shows I am missing client tests for the Leg type

Would you mind to add a test so that we can be "less carefull" :) ?
