### ISSUE TITLE
Unusual bicycle detour route produced

### ISSUE THREAD

**Issue by jengelh** [graphhopper/graphhopper#1505]
https://graphhopper.com/maps/?point=51.502084%2C9.710246&point=51.502612%2C9.716957&locale=en-US&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

For some reason, GH proposes a route via road K202. I could speculate that it might prefer roads where HGV are banned (maxweight=7.5t on K202), but that theory might be a bit far fetched.

What it does:
![x](https://user-images.githubusercontent.com/8861948/49973900-37d83300-ff37-11e8-8456-fcd3d2d8fd90.png)

What I think it should do instead:
![y](https://user-images.githubusercontent.com/8861948/49973893-30b12500-ff37-11e8-910a-05025bc130f0.png)

**Comment by ratrun** [comment]
This ticket can be closed. The proposed solution is choosen now.

**Comment by jengelh** [comment]
Still unusual routing
https://graphhopper.com/maps/?point=51.502138%2C9.709892&point=51.502625%2C9.717198&locale=en-US&elevation=true&vehicle=bike&weighting=fastest&use_miles=false&selected_detail=Elevation&layer=Omniscale

**Comment by ratrun** [comment]
Ok. You changed your example slightly. There is a threshold, and in this example it is actuylly very close. In the ordinary bike profile we prefer `highway=residential` over `highway=secondary`, even if the distance becomes longer. This is because `highway=secondary` is in the list for the avoided highway types. We assume much more traffic there and I believe this is correct.
If you change to the racing bike profile your proposed solution is chosen. 
I therefore propose to close this issue.
