### ISSUE TITLE
Inconsistent name traversal ID vs. traversal key vs edge key

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1549]
I would propose to rename everything to "edge key"

**Comment by easbar** [comment]
I think traversal id makes sense because it can be either the node id (for node-based routing) or an edge key (for edge-based routing). But yes I think traversal key and edge key are used interchangeably.

**Comment by karussell** [comment]
Hmmh, maybe they are indeed two things: 1. the traversal key, used for the algorithm and 2. the edge key, used for fetching the edge state ala graph.getEdgeIteratorState(edgeKey).

**Comment by karussell** [comment]
@easbar Do you think we should introduce these 2 breaking changes to make the naming more consistent?

 * public TraversalMode.createTraversalId => traversalMode.createTraversalKey
 * protected AbstractBidirAlgo.getTraversalId => AbstractBidirAlgo.getTraversalKey

**Comment by easbar** [comment]
Sorry for not getting back to this in time, I think changing the occurrences of traversal key to traversal id might have been slightly less 'breaking' but I think this way it is also fine.

**Comment by karussell** [comment]
Ah, good point. Will investigate.

**Comment by karussell** [comment]
This was indeed better - thanks!

**Comment by michaz** [comment]
Speaking of which, I have another question about terminology: What exactly does the word "state" refer to, in "fetching the edge state" and `EdgeIteratorState`? I mean, what is "state" about it? I never understood that.

**Comment by easbar** [comment]
My (personal) explanation for this: We use `edge` in many places where we mean the ID of an edge. So `edge` is kind of taken already and when we want to refer to the actual 'edge' we call it 'edge state'. I think its also called 'state', because its a possible 'value' of an edge *iterator* (the iterator cycles through different states (=edges))...

**Comment by michaz** [comment]
I see, yes. I think the terminology is a bit unusual, but then, also our way of doing this is a bit unusual, so perhaps there isn't an obviously better word.

I think _approximately_ I would call `EdgeIterator` --> `EdgeCursor` (I think cursor is the usual word for a thing on which you can say `next()` and which changes _itself_ in place.
I would call a _detached_ `EdgeIteratorState` `EdgeData`, but not a _non_-detached one, because `Data` in this context often implies immutability.

Tricky.

**Comment by michaz** [comment]
I think I just find `State` confusing because it isn't clear to me whether it's the state of the iterator, or the state of the edge, or the two just got mixed up because they are so close to each other. ,-)

**Comment by karussell** [comment]
Yeah, as @easbar said, the naming `state` is because an `EdgeIterator` can be used as "edge" providing the `distance` etc and if `next()` is called the same object has now a different state. But yeah, we can use EdgeCursor if you prefer. I think this is also the term used to traverse through the rows in SQL world which is very similar to what we do here.
