### ISSUE TITLE
Rare bug for stall on demand

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1574]
Currently I'm facing an issue when stall_on_demand=true (if false it disappears). It is very rare and hard to reproduce in a unit test.

The reason is likely in DijkstraBidirectionCH.entryIsStallable:
```
adjNode.weight + weighting.calcWeight(iter, !reverse, getIncomingEdge(entry)) < entry.weight
```

It returns true although it should return false. In my case it is the 4th decimal place: `35.643+50.2975 < 50.297522`

So, when I round to the precision we currently use in CHGraphImpl:
`Math.round(entry.weight / 1000f) * 1000f`
the problem disappears. But maybe it is related to virtual nodes because the special case is a QueryGraph with 3 locations where the fastest route B->C crosses point A.

**Comment by easbar** [comment]
Thanks a lot for debugging, I am sure this took a lot of time to figure out. Quite suprisingly I think I ran into the same issue recently and could narrow it down to this:

map: `core/files/andorra.osm.pbf`
query: `http://localhost:8989/maps/?point=42.486984%2C1.493152&point=42.479172%2C1.492451&point=42.577133%2C1.458908&locale=en-US&vehicle=car&weighting=fastest&elevation=false&stall_on_demand=true&use_miles=false&layer=Omniscale`

It is also related to the via point (removing it or even changing the order of the points) makes the problem dissapear, just as well as setting stall_on_demand to false.

Interestingly this problem does not happen on more recent versions of the same map (the oldest I found was still from 2018), so might be an option to diff the maps to see what has changed.

If it turns out that the problem is due to the floating point number comparison I think we could simply use some epsilon in the above condition.

> So, when I round to the precision we currently use in CHGraphImpl:

What did you round exactly ?

**Comment by karussell** [comment]
Interesting, indeed :) !

> Exactly which numbers did you round ?

I meant that I used 
```java
adjNode.weight + weighting.calcWeight(iter, !reverse, getIncomingEdge(entry)) < Math.round(entry.weight / 1000f) * 1000f
// (We could also use `entry.weight - 1/1000f`)
```
instead of
```java
adjNode.weight + weighting.calcWeight(iter, !reverse, getIncomingEdge(entry)) < entry.weight
```

The reason for the 1000f is [the precision we use for the shortcut weight in CHGraphImpl](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/CHGraphImpl.java#L47). I also think that we could reduce the change that this happens via increasing the precision of the shortcut weight #1544.

Another wild guess for the reason: the shortcut weight precision is limited to the 1000f compared to the very precise weight calculated from two VirtualEdgeIteratorState's?

**Comment by easbar** [comment]
> Another wild guess for the reason: the shortcut weight precision is limited to the 1000f compared to the very precise weight calculated from two VirtualEdgeIteratorState's?

I also remember recently having problems with virtual edges that did not seem to have the right distance (I'm on it :))

**Comment by easbar** [comment]
I have a failing integration test here: https://github.com/graphhopper/graphhopper/tree/issue_1574

There are many ways to make it pass:

- as @karussell suggested fixing the stall on demand condition (rounding)
- do not add geometries during parsing the map
- do not set roundabout bits during parsing
- increasing the min subnetwork size

I have tried to reproduce the problem by building the graph manually using `graph.edge...` using the output of `GHUtility.printGraphForUnitTest`, but unfortunately to no avail so far :(

**Comment by easbar** [comment]
> Math.round(entry.weight / 1000f) * 1000f

It should be `Math.round(entry.weight*1000f)/1000f`, probably what you meant. The other formula returns zero for all weights < 1000, so basically always (-> nothing gets stalled).

Anyway I am now 99.9% sure think I finally understood the problem and it is related to CH/stall-on-demand and virtual via nodes. Removing the geometries, not using the roundabout bit or using another subnetwork size only fixes the problem because another hierarchy is created I guess.

**Comment by karussell** [comment]
> probably what you meant.

Ups! Sure!

>I have a failing integration test here: https://github.com/graphhopper/graphhopper/tree/issue_1574

Great. Will also have a look and guess about it

**Comment by easbar** [comment]
https://github.com/graphhopper/graphhopper/blob/f63b30ccbf37d9558c830b61a7608d3bc19b4a2c/core/src/test/java/com/graphhopper/routing/ch/PrepareContractionHierarchiesTest.java#L425-L434

**Comment by easbar** [comment]
I am wondering if an option would be to set the CH level of virtual nodes to the minimum CH level of their neighbornodes (can be virtual nodes as well). Right now we do this (imagine the vertical position to represent the CH level) and x to be virtual nodes (could be multiple).
```
           b           
  a             

    x x x
```
which allows going 'down' from a to b because of the virtual node(s). so instead do this: 
```
            b 
  a  x x x      
```

This way the virtual nodes should not change the behavior of CH ? Another way would be to ignore via virtual nodes completely: first find the closest 'real node' from virtual start/target nodes on the query graph, ther run CH on the plain CH graph (without virtual edges). Finally we could of course try to fix the rounding in certain places...

**Comment by karussell** [comment]
> I could reproduce the bug in a unit test with only 8 nodes, it is quite involved

Really great you got something recreated :+1: 

> I am wondering if an option would be to set the CH level of virtual nodes to the minimum CH level of their neighbornodes 

Sounds reasonable but why would this fix the problem? Isn't this even more restrictive?

> first find the closest 'real node' from virtual start/target nodes on the query graph, then run CH on the plain CH graph (without virtual edges)

This is cumbersome. I tried this for non-CH (i.e. without the QueryGraph logic) but the search got too complex. Best thing would be of course we could hide the virtual node complexity for the algorithms (but this is also not fully possible for landmarks)
