### ISSUE TITLE
distance_limit without time_limit isn't that intuitive for the Isochrone API

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1607]
Currently we allow a distance_limit for the Isochrone API. This was good for use cases like "calculate a delivery area but roughly base it on distance not on the time". But explaining this property, i.e. what this it means in the time-based Isochrone API is difficult.

If you see distance_limit as an additional constraint as suggested from @oblonski (additionally to the time_limit) it makes more sense. With time_limit=very_big_number converts into the current situation.

**Comment by michaz** [comment]
Careful here: Those aren't _constraints_ when talking about isolines. They're only something like constraints when you calculate the shortest path tree, and at some point you stop calculating. But with isolines, you calculate _the isoline for 6 minutes_, or _the isoline for 5 km_. (That's why `_limit` isn't a very accurate name.)

I think it makes most sense the way it is (apart from the name): You specify _either_ a distance (or several) _or_ a time (or several).

**Comment by michaz** [comment]
See also #1979. The a) objective function, b) the search limit, _and_ c) the function we want the isoline for, are (potentially) _three_ different things.

a) directs the search. We get _different values_ for b) and c) depending on how a) is set.
b) needs to be high enough so a value for c) is available at every point
c) determines where the polygon(s) go through the point set

**Comment by karussell** [comment]
Thanks, for fixing this and with the clear explanation the "strange" use case (weighting=fastest plus distance_limit) makes sense to me now too.
