### ISSUE TITLE
Zip Path Traversal 

### ISSUE THREAD

**Issue by akyzi007** [graphhopper/graphhopper#1628]
Getting the following warning from Google play store.
Zip Path Traversal
Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.
https://support.google.com/faqs/answer/9294009

Vulnerable locations:
com.graphhopper.util.Unzipper.unzip

Here is the dependency in may app.build
  implementation(group: 'com.graphhopper', name: 'graphhopper-core', version: '0.13-SNAPSHOT') {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
        exclude group: 'org.openstreetmap.osmosis', module: 'osmosis-osm-binary'
        exclude group: 'org.apache.xmlgraphics', module: 'xmlgraphics-commons'
    }

I have tried graphhoper 010-SNAPSHOT, 012-SNAPSHOT, and even 013-SNAPSHOT versions but facing the same issue. 
I am using pocketmaps project for offline maps. I also tried to upgrade and downgrade the pocket maps dependencies to see if the error removes but no luck.
Can you please guide me regarding this. I have been trying to understand the issue but so far no luck.
Thank you

**Comment by mprins** [comment]
Details/explanation and a possible fix on zip slip vulnerability: https://snyk.io/research/zip-slip-vulnerability

The code path may not be used in your android app, I haven't checked, so the warning may not be anything to worry about for the app (false positive).

It could be useful to set up the project with a free service like Snyk (https://snyk.io/plans/) to run code inspections

**Comment by akyzi007** [comment]
Thank you for you response. I am looking into it. 
One thing I can confirm is, the class and method name ( com.graphhopper.util.Unzipper.unzip ) specified in the google warning is not called from application.

**Comment by karussell** [comment]
Thanks for reporting! Have fixed this via the suggestion from snyk. This is important when you do not trust the app developer. If you have your own map files, this does not matter IMO.

Thanks @mprins for the link - have now set up snyk for this repo. Usually github also has an alert system, but snyk is probably more advanced with Java.

Additionally I have updated our maps data so that it will work for the current snapshot version 0.13 (failed before due to the wrong location index version)
