### ISSUE TITLE
Possible routing error: Preference of highway=footway over highway=residential

### ISSUE THREAD

**Issue by ltog** [graphhopper/graphhopper#1681]
**Important note: https://www.openstreetmap.org/changeset/73198089 changed the situation described in this issue by adding stairs on the footway.**

From: 8FVC7HG8+7H
To: 8FVC7HG9+95

Routing looks like this:

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=47.27557%2C8.56648%3B47.27566%2C8.56822#map=19/47.27580/8.56732
(going over Holzgasse, a `highway=footway`)

![bad](https://user-images.githubusercontent.com/4726277/62486036-7ec4b280-b7be-11e9-942d-b54f2b9e9830.png)

but IMHO should look like this:

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=47.27557%2C8.56648%3B47.27566%2C8.56822#map=18/47.27618/8.56703
(going the longer way over Hintere Bergstrasse, a `highway=residential`)

![good](https://user-images.githubusercontent.com/4726277/62486048-85532a00-b7be-11e9-84e2-dab5bd68fbae.png)

My understanding of https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway is that bicycles should not be routed there unless there is also a `bicycle=yes` (which is not the case in this example).

The same behaviour occurs in OsmAnd: https://github.com/osmandapp/Osmand/issues/7372

Edit: Fix link

**Comment by karussell** [comment]
If you get off the bike and if you are still faster shouldn't we pick this route?

There might be still something wrong - highly likely something with the elevation as the other profiles seem to work fine. (especially now that there are stairs)

**Comment by karussell** [comment]
[The average_speed is as expected only 6km/h](https://graphhopper.com/maps/?point=47.275622%2C8.566466&point=47.27566%2C8.56822&vehicle=bike&details=average_speed&debug=true)

![image](https://user-images.githubusercontent.com/129644/62877706-eda68c00-bd27-11e9-9f5e-0198dd4a1f72.png)

The alternative route is partly 10km/h (otherwise 18km/h)

![image](https://user-images.githubusercontent.com/129644/62877786-14fd5900-bd28-11e9-89b5-50674d5370f3.png)

The reverse directions is likely ok, because uphill the 6km/h is a 2km/h.

Of course bike is more than just speed, but in this example highly likely the problem. The data update will come soonish (we had an issue in our auto deployment pipeline)

**Comment by ltog** [comment]
> If you get off the bike and if you are still faster shouldn't we pick this route?

Fair question. I don't know. Would this question warrant the creation of a corresponding configuration setting?

**Comment by karussell** [comment]
A configuration option that can be send per request will come (currently it is even required to code in Java), but it will likely not be available from the UI and probably take even more months (see [this work](https://discuss.graphhopper.com/t/flexible-vehicle-profiles/3612)). Still we need some default value :)

**Comment by karussell** [comment]
Can we close here?

**Comment by ltog** [comment]
To summarize: Graphhopper routes over the footway instead of the residential street, since it's significantly shorter and indicates to the user that he/she has to get off the bicycle?

Sounds fair to me... So this issue can be closed.
