### ISSUE TITLE
"Walking at night" routing to route preferring well lit/open spaces

### ISSUE THREAD

**Issue by yoasif** [graphhopper/graphhopper#1737]
See: https://twitter.com/kanocarra/status/1175876911958044672

>I wish Google Maps had a "I'm walking home by myself at night" mode that would show you a way with well lit paths and open spaces. It always seems to take you on narrow, dark pathways in cities

**Comment by karussell** [comment]
This is already doable (see [here](https://github.com/karussell/nordhopper)), but IMO it cannot be integrated in the standard walking profile, because for the general "safe at night" requirement this is not sufficient and it always needs additional (country specific) knowledge. So it more bowls down to integrate data from OSM (which is easy now with the TagParsers) or external data (depending on a specific use case) and then use this to calculate the path costs. So this is an interesting use case but we won't fix it. Of course you can make it easier to implement via providing pull requests in this direction. At the same time [we will make this also easier](https://discuss.graphhopper.com/t/work-towards-more-configurable-vehicle-profiles/4708).
