### ISSUE TITLE
Remove `ch.force_heading` and do not allow `pass_through` for node-based CH

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1763]
Heading and `pass_through` does not really work with node-based CH (even though there are cases where it works). Right now there is an extra `ch.force_heading` parameter that can be set to allow it anyway. Do we need to keep this ? Should `pass_through` not also be forbidden for node-based CH (unless `ch.force_heading` is set) ? 

On the other hand supporting `heading` and `pass_through` for edge-based CH should be possible. Would be nice to have now that we have edge-based CH ?

@devemux86 ?

related: #1697, #1647, #1765

**Comment by devemux86** [comment]
One of the reasons the flexible mode remains the preferred option in vehicle navigation is because it has features like [heading](https://github.com/graphhopper/graphhopper/blob/master/docs/core/routing.md#heading) (in degrees), besides the (previous) main benefit of [turn restrictions](https://github.com/graphhopper/graphhopper/blob/master/docs/core/turn-restrictions.md).

If speed mode manages to have also the heading after turn restrictions, that would be awesome. :slightly_smiling_face:

**Comment by easbar** [comment]
And are you using heading with speed mode (currently broken and requires `ch.force_heading=true`) ?

**Comment by devemux86** [comment]
> And are you currently using heading with speed mode (currently broken and requires ch.force_heading=true) ?

No, I use those features only with flexible mode.

**Comment by karussell** [comment]
> Do we need to keep this ? 

No

> Should pass_through not also be forbidden for node-based CH 

Yes

> Would be nice to have now that we have edge-based CH ?

Yes :)

**Comment by easbar** [comment]
For `pass_through` support with speed mode see #1765, for `heading` the best you can do atm is using edge-based CH with `curbside` parameters (see #1697). Sooner or later we should implement heading with edge-based CH.
