### ISSUE TITLE
Add support for time dependent routing

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#1781]
I noticed that @michaz is currently adding time dependence to some of the routing algorithms in the [block-core](https://github.com/graphhopper/graphhopper/tree/block-core) branch in order to support conditional access. (i only glimpsed over the changes, so i might be wrong here)

Could we take this a step further and add basic support for time dependent routing? The idea would be to extend our existing algorithms to solve the Time Dependent Vehicle Routing Problem with Time Windows.

@karussell  I'm aware that this might compete a bit with your [Time-Dependent Route Optimization API](https://www.graphhopper.com/blog/2017/11/06/time-dependent-optimization/) but i thought that i should at least ask.

**Comment by karussell** [comment]
> @karussell I'm aware that this might compete a bit with your Time-Dependent Route Optimization API but i thought that i should at least ask

No, not really. We usually open source 100% of the routing engine and see also the [bottom of our open source page](https://www.graphhopper.com/open-source/). The blog post is about "route optimization" (see [our wording/differentiation](https://www.graphhopper.com/blog/2017/09/18/route-optimization-explained/)) which is a different beast due to the performance requirements of the matrix and other stuff. And if we do not open source something of the routing engine like the truck profiles only because it is either in-progress, or too ugly or requires a closed source data source.

**Comment by otbutz** [comment]
> And if we do not open source something of the routing engine like the truck profiles we do this only because it is either in-progress, or too ugly **or requires a closed source data source**.

I agree that i doesn't make much sense to add support for time dependent routing if we only target a commercial service which is not available to every user. TomTom also seems to provide the data in a non-proprietary format that would allow users to create their own time profiles based on data from e.g. fleet management.

Even the ability to just change the "effective" speed for some selected routes which tend to be a huge bottleneck would be awesome. The Elbe Tunnel in Hamburg is a good example for this. The difference between effective speed and legally allowed speed on this route is huge during rush hours.

With an example route of ~13km:
* [Graphhopper](https://graphhopper.com/maps/?point=53.613081%2C9.914646&point=53.512117%2C9.914196&locale=de&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale): 11minutes
* [Google Maps](https://www.google.com/maps/dir/'53.613081,9.914646'/'53.512117,9.914196'/@53.5626641,9.8453917,24057m/data=!3m2!1e3!4b1!4m14!4m13!1m3!2m2!1d9.914646!2d53.613081!1m3!2m2!1d9.914196!2d53.512117!2m3!6e0!7e2!8j1577203200!3e0!5m1!1e1): 35minutes (during the rush hour around 4pm)

**Comment by karussell** [comment]
Probably you misunderstood what I meant: we will add time-dependent routing. 

Please note that this is a different topic from improving ETAs (#382) or including historic traffic data. Also please note that although TomTom provides a non-propretary format it does not make any sense to support this, because if you use TomTom data you use their proprietary data format anyway because you can use their ID mapping and if you use OSM road network then you are not allowed to use TomTom traffic data as overlay (license).

> The Elbe Tunnel in Hamburg is a good example for this. The difference between effective speed and legally allowed speed on this route is huge during rush hours.

Sure, but how would you solve this in an open source project? We could create a separate open source project that either aggregates data or defines areas and times for different vehicle speed. But this is a huge effort and we certainly will fail if we do this without a broader community support.

**Comment by otbutz** [comment]
> Please note that this is a different topic from improving ETAs (#382) or including historic traffic data.

I'm aware that the current efforts are intended for a different use case but i thought it might be a good point to bring the historic traffic topic up for discussion.

> if you use OSM road network then you are not allowed to use TomTom traffic data as overlay (license).

Are you sure about that?

https://developer.tomtom.com/terms-and-conditions
> 12.5. You shall be permitted to display TomTom Maps APIs Results on third party content or map data provided that nothing shall add or incorporate Results into the OSM or any other open source database. You shall also be permitted to display Results from third party content or map data on a TomTom map as a separate layer.


> Sure, but how would you solve this in an open source project? We could create a separate open source project that either aggregates data or defines areas and times for different vehicle speed. But this is a huge effort and we certainly will fail if we do this without a broader community support.

I wholeheartedly agree that effort of gathering and compiling the data needed to compete with commercial offerings is huge but we don't have to aim that high. It would be sufficient to start with an open format which allows us to manipulate speeds for certain time windows.

This way we could support multiple commercial providers and ultimately speed profiles compiled from open traffic data.

**Comment by karussell** [comment]
> Are you sure about that?

Yes, because using their APIs license is not the same license when using their raw road network data.

> compiling the data needed to compete with commercial offerings is huge

I don't think it is huge, we could do it step by step, region by region and additionally pick open data where available: https://github.com/graphhopper/open-traffic-collection

But someone has to do it and we would love to join and support it :)

> It would be sufficient to start with an open format which allows us to manipulate speeds for certain time windows.

Yes, sure. Again, we would support such an initiative but we currently have no priority to push this. Additionally this is not the scope of this repo (the routing engine).

**Comment by michaz** [comment]
> Could we take this a step further and add basic support for time dependent routing?

Hey, let me re-emphasize that we *will* add basic support for time-dependent routing to GraphHopper in the near future. We will keep the interface open enough so that any OSM-like data source can be used with reasonable effort.

What may happen is that the interface we will eventually publish will just be a functional interface for a time-dependent weight- and travel-time function by link, and the implementor will be in charge of finding a way to import and store the data "on the side". I'm not sure I want to define and provide a general data structure for this, as the best one may be a different one for every use case. 

(Just override a couple of links with special travel times != import hourly historic traffic data for a week for the entire world.)

**Comment by dteirney** [comment]
@michaz or @karussell is there a good place to follow for further information or any plans that might be brewing regarding time dependent routing?
