### ISSUE TITLE
Consider "edge based"-only subnetworks

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1807]
It is possible to create "edge based"-only subnetworks so we should likely make the subnetwork removal edge-based or rework the mechanism. E.g. [this turn relation](https://www.openstreetmap.org/relation/5882938) disallows the access of cars into the subnetwork from North and [this oneway](https://www.openstreetmap.org/way/31814405) blocks access from West (which is probably a mapping error).

Leading to "Connection between locations not found" - [link](https://graphhopper.com/maps/?point=51.433411%2C7.00939&point=51.433036%2C7.010147&ch.disable=true).

Here is a screenshot of the situation: There is a 'straight-only' turn relation at the junction between Franziskastraße and Gudulastraße which restricts access to Gudulastraße, but at the same time its not accessible from the West/South, because it is a one-way:

![image](https://user-images.githubusercontent.com/17603532/82427920-09df1280-9a8a-11ea-9745-6d8bed1b31b0.png)

**Comment by easbar** [comment]
Hmm depending on whether or not we remove such subnetworks either the location lookup or the routing fails. Not sure whats better to be honest :) But its certainly useful to be able to detect such subnetworks so they can be reported as mapping errors.

**Comment by karussell** [comment]
An edge-based subnetwork removal would improve the situation. The location index would often not fail and instead it would snap to the "main land" and would then allow routing to be done without the "connection not found" error.

**Comment by easbar** [comment]
> An edge-based subnetwork removal would improve the situation. After the removal the location index would often not fail and instead it would snap to the "main land" and would then allow routing to be done without the "connection not found" error.

Yes I think I agree. But still when snapping to the main land a user might be just as confused about the point snapping to the mainland as she might be confused about the route not being found. The real problem is the bad mapping in this case and ideally **this** should be somehow reported to the user. Maybe this can be achieved by not removing the subnetwork in the first place and reporting something like 'start and target locations belong to different networks (probably due to bad OSM data)'. Of course this would only be an improvement if the user has the option to 'not snap to isolated networks' or something...

**Comment by karussell** [comment]
> But still when snapping to the main land a user might be just as confused about the point snapping to the mainland as she might be confused about the route not being found.

Yeah, that was what I also thought, especially because OSM improves, but most users disagree :) ... if you have dozens or hundred of points and many such requests then you prefer that this is automatically done.

> The real problem is the bad mapping in this case and ideally this should be somehow reported to the user.

Yes, in this case. But what are you doing if you have a small network behind "private" barriers? Or where signs with specific limits to e.g. weight introduce such islands for only some bigger trucks or in the future for some dynamically configured vehicle?

> Maybe this can be achieved by not removing the subnetwork in the first place and reporting something like 'start and target locations belong to different networks (probably due to bad OSM data)'

Do you mean reporting or forcing? Reporting does not really solve the problem for users. (BTW: [we already do something like this for landmarks](https://graphhopper.com/maps/?point=46.073231%2C1.757813&point=40.713956%2C-93.164062&ch.disable=true))

And forcing, yes, this would mainly solve the issue, except when, by accident, you start with a location with the wrong subnetwork number and the following locations (e.g. EdgeFilter forces to same number) will have a different subnetwork number and so the request will fail. Still we would need to store more than 1 byte per node.

**Comment by karussell** [comment]
> not snap to isolated networks

How would you define this? There were cases where we removed smaller networks that were real islands and where it would be ok to calculate routes, and then there were other huge subnetworks that were the private roads of the DESY collider. 

What we basically would need to solve all these details is that we already start the search while the lookup.

**Comment by easbar** [comment]
Ok I'm convinced :) Lets just make the subnetwork seach edge-based for now.

> Do you mean reporting or forcing?

I meant reporting. Reporting would be useful to the user if there was an additional flag like 'allow_snapping_to_subnetworks=false' (and make 'false' the default to resemble the current behavior).

> How would you define this?

We could do it just as we do it now (use the min subnetwork size to define which subnetworks are 'isolated', just instead of removing them tag them as 'isolated', so at query time we can decide whether we should snap to the main network or snap to the isolated subnetwork (potentially risking a connection not found error)).

**Comment by karussell** [comment]
> use the min subnetwork size to define which subnetworks are 'isolated'

This is a very good idea, that would cost us also only one bit per node or edge and we could improve the current situation.

**Comment by easbar** [comment]
Another possible solution here would be implementing the turn restrictions as soft constraints, but this only really works as long as we can assume the weightings to be time-based.
