### ISSUE TITLE
*Unrecognized field at: server.application_connectors

### ISSUE THREAD

**Issue by JeongJun-Lee** [graphhopper/graphhopper#1925]
**Describe the bug**
A clear and concise description of what the bug is. If you are unsure if this is really a bug, please create a new topic in [our forum](https://discuss.graphhopper.com/c/graphhopper).

If you have an Android application that uses GraphHopper, please always post to the [forum](https://discuss.graphhopper.com/c/graphhopper/graphhopper-ios-and-android) before and include logs and the version of
your Android system.

**To Reproduce**
java -Dgraphhopper.datareader.file=uzbekistan-latest.osm.pbf -jar *.jar server config-example.yml

**Expected behavior**
Should be no error

**System Information**
GraphHopper: 0.13
MacOS: 10.13.6
JRE: 1.8.0_121

**Screenshots & Logs**
io.dropwizard.configuration.ConfigurationParsingException: config-example.yml has an error:
  * Unrecognized field at: server.application_connectors
    Did you mean?:
      - applicationConnectors
      - applicationContextPath
      - adminConnectors
      - adminMinThreads
      - allowedMethods
        [22 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)

**Comment by karussell** [comment]
Please either use the master branch and the config-example.yml OR use the branch 0.13 and the [config-example.yml](https://github.com/graphhopper/graphhopper/blob/0.13/config-example.yml) there.

**Comment by JeongJun-Lee** [comment]
Thanks for quick response. I just download as being written at the guideline : https://github.com/graphhopper/graphhopper/blob/0.13/docs/web/quickstart.md. The link's URL may be wrong. The doc should be updated.

**Comment by karussell** [comment]
Ah, indeed - have fixed the link. Thanks!

**Comment by feiercrack** [comment]
nope. still not running.

java -Dgraphhopper.datareader.file=berlin-latest.osm.pbf -jar graphhopper-web-0.13.0.jar server config-example.yml
io.dropwizard.configuration.ConfigurationParsingException: config-example.yml has an error:
  * Failed to parse configuration; Cannot construct instance of `com.graphhopper.http.GraphHopperServerConfiguration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <link rel="dns-prefetch" href="https://github.githubassets.com"> <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com"> <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com"> <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">


<link crossorigin="anonymous" media="all" integrity="sha512-ZUjVod2EvYMDbGqRSyW0rpfgBq3i+gnR/4PfrzLsy5f20oIcRfgFQFVKgi3Ztp917bP1K/kdP5q8+nAlJ3+cFA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-6548d5a1dd84bd83036c6a914b25b4ae.css" />
<link crossorigin="anonymous" media="all" integrity="sha512-aX4OkLpzulpadvOncEEPpJZnQyeKNm2npzJowbL5JxptkoZXNPPy61R059xmEa3YyVF4Y4YXB6g+5o08uvdWpA==" rel="stylesheet" href="https://github.githubassets.com/assets/github-697e0e90ba73ba5a5a76f3a770410fa4.css" />





<meta name="viewport" content="width=device-width">
<title>graphhopper/config-example.yml at 0.13 ┬À graphhopper/graphhopper</title> <meta name="description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper"> <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub"> <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub"> <meta property="fb:app_id" content="1401488693436528">
<meta name="twitter:image:src" content="https://repository-images.githubusercontent.com/3480666/ab93f880-d9ff-11e9-80cb-e7ef95dbcd84" /><meta name="twitter:site" content="@github" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content="graphhopper/graphhopper" /><meta name="twitter:description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper" /> <meta property="og:image" content="https://repository-images.githubusercontent.com/3480666/ab93f880-d9ff-11e9-80cb-e7ef95dbcd84" /><meta property="og:site_name" content="GitHub" /><meta property="og:type" content="object" /><meta property="og:title" content="graphhopper/graphhopper" /><meta property="og:url" content="https://github.com/graphhopper/graphhopper" /><meta property="og:description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper" />
<link rel="assets" href="https://github.githubassets.com/"> <link rel="web-socket" href="wss://live.github.com/_sockets/VjI6NTAxNjk3MjU5OjIyNjk1MWJkMTdkZTZhYTQyNWUxYzI1OWVkOGIwNmY0ZjkwZTM5NzM4ZTY2MGUwYWJmMzdhZTM5NWZjNzE4NDk=--fa92bdeaa5ee8e33417f191fc0eba88a12857fdb"> <link rel="sudo-modal" href="/sessions/sudo_modal">
<meta name="request-id" content="17F2:1C90:22ACB4:330C47:5E545EC3" data-pjax-transient="true" /><meta name="html-safe-nonce" content="cdc91887cc8701d96bba0188a81d4d41cdf3a4f8" data-pjax-transient="true" /><meta name="visitor-payload" content="eyJyZWZlcnJlciI6Imh0dHBzOi8vZ2l0aHViLmNvbS9ncmFwaGhvcHBlci9ncmFwaGhvcHBlci9pc3N1ZXMvMTkyNSIsInJlcXVlc3RfaWQiOiIxN0YyOjFDOTA6MjJBQ0I0OjMzMEM0Nzo1RTU0NUVDMyIsInZpc2l0b3JfaWQiOiIzOTgxMjUyODcwNDE4NTYyNzQ4IiwicmVnaW9uX2VkZ2UiOiJhbXMiLCJyZWdpb25fcmVuZGVyIjoiaWFkIn0=" data-pjax-transient="true" /><meta name="visitor-hmac" content="d606b198799a1c4927a59cc3bdb178bb353227e36ecc2805dbe8145b8093e6b8" data-pjax-transient="true" />


<meta name="github-keyboard-shortcuts" content="repository,source-code" data-pjax-transient="true" />


<meta name="selected-link" value="repo_source" data-pjax-transient>
<meta name="google-site-verification" content="KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU"> <meta name="google-site-verification" content="ZzhVyEFwb7w3e0-uOTltm8Jsck2F5StVihD0exw2fsA"> <meta name="google-site-verification" content="GXs5KoUUkNCoaAZn7wPN-t01Pywp9M3sEjnt_3_ZWPc">
<meta name="octolytics-host" content="collector.githubapp.com" /><meta name="octolytics-app-id" content="github" /><meta name="octolytics-event-url" content="https://collector.githubapp.com/github-external/browser_event" /><meta name="octolytics-dimension-ga_id" content="" class="js-octo-ga-id" /><meta name="octolytics-actor-id" content="47046040" /><meta name="octolytics-actor-login" content="feiercrack" /><meta name="octolytics-actor-hash" content="fd8ae89a9b495f81ce4c831de99898cb5eb79689e9bd54d6157b2dbb59ae9562" /> <meta name="analytics-location" content="/&lt;user-name&gt;/&lt;repo-name&gt;/blob/show" data-pjax-transient="true" />


<meta name="google-analytics" content="UA-3769691-2">
<meta class="js-ga-set" name="userId" content="7675ec213c7269ffaab9de6fa08aec67">
<meta class="js-ga-set" name="dimension1" content="Logged In">




<meta name="hostname" content="github.com"> <meta name="user-login" content="feiercrack">
<meta name="expected-hostname" content="github.com">
<meta name="js-proxy-site-detection-payload" content="OGNjNWQ5MGNhODJkZGQzYmQ5YjU0ODk2ZGQ4OGM3ODZhNTQzNDc1ZTQxMGNmZWUyNzgyYmZiNTBlZjc2ZmJmOXx7InJlbW90ZV9hZGRyZXNzIjoiODkuMjQ2LjEyMS4yMiIsInJlcXVlc3RfaWQiOiIxN0YyOjFDOTA6MjJBQ0I0OjMzMEM0Nzo1RTU0NUVDMyIsInRpbWVzdGFtcCI6MTU4MjU4NzYxOSwiaG9zdCI6ImdpdGh1Yi5jb20ifQ==">
<meta name="enabled-features" content="MARKETPLACE_FEATURED_BLOG_POSTS,MARKETPLACE_INVOICED_BILLING,MARKETPLACE_SOCIAL_PROOF_CUSTOMERS,MARKETPLACE_TRENDING_SOCIAL_PROOF,MARKETPLACE_RECOMMENDATIONS,MARKETPLACE_PENDING_INSTALLATIONS,RELATED_ISSUES,GHE_CLOUD_TRIAL">
<meta http-equiv="x-pjax-version" content="8310d593c1cc38b86be83242de7e6f3f">

<link href="https://github.com/graphhopper/graphhopper/commits/0.13.atom" rel="alternate" title="Recent Commits to graphhopper:0.13" type="application/atom+xml">
<meta name="go-import" content="github.com/graphhopper/graphhopper git https://github.com/graphhopper/graphhopper.git">
<meta name="octolytics-dimension-user_id" content="2264498" /><meta name="octolytics-dimension-user_login" content="graphhopper" /><meta name="octolytics-dimension-repository_id" content="3480666" /><meta name="octolytics-dimension-repository_nwo" content="graphhopper/graphhopper" /><meta name="octolytics-dimension-repository_public" content="true" /><meta name="octolytics-dimension-repository_is_fork" content="false" /><meta name="octolytics-dimension-repository_network_root_id" content="3480666" /><meta name="octolytics-dimension-repository_network_root_nwo" content="graphhopper/graphhopper" /><meta name="octolytics-dimension-repository_explore_github_marketplace_ci_cta_shown" content="false" />

<link rel="canonical" href="https://github.com/graphhopper/graphhopper/blob/0.13/config-example.yml" data-pjax-transient>

<meta name="browser-stats-url" content="https://api.github.com/_private/browser/stats">
<meta name="browser-errors-url" content="https://api.github.com/_private/browser/errors">
<link rel="mask-icon" href="https://github.githubassets.com/pinned-octocat.svg" color="#000000"> <link rel="icon" type="image/x-icon" class="js-site-favicon" href="https://github.githubassets.com/favicon.ico">
<meta name="theme-color" content="#1e2327">

<link rel="manifest" href="/manifest.json" crossOrigin="use-credentials">
</head>
<body class="logged-in env-production page-responsive page-blob">

<div class="position-relative js-header-wrapper "> <a href="#start-of-content" tabindex="1" class="p-3 bg-blue text-white show-on-focus js-skip-to-content">Skip to content</a> <span class="Progress progress-pjax-loader position-fixed width-full js-pjax-loader-bar"> <span class="progress-pjax-loader-bar top-0 left-0" style="width')
 at [Source: UNKNOWN; line: -1, column: -1]

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:156)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.graphhopper.http.GraphHopperServerConfiguration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <link rel="dns-prefetch" href="https://github.githubassets.com"> <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com"> <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com"> <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com"> <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">


<link crossorigin="anonymous" media="all" integrity="sha512-ZUjVod2EvYMDbGqRSyW0rpfgBq3i+gnR/4PfrzLsy5f20oIcRfgFQFVKgi3Ztp917bP1K/kdP5q8+nAlJ3+cFA==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-6548d5a1dd84bd83036c6a914b25b4ae.css" />
<link crossorigin="anonymous" media="all" integrity="sha512-aX4OkLpzulpadvOncEEPpJZnQyeKNm2npzJowbL5JxptkoZXNPPy61R059xmEa3YyVF4Y4YXB6g+5o08uvdWpA==" rel="stylesheet" href="https://github.githubassets.com/assets/github-697e0e90ba73ba5a5a76f3a770410fa4.css" />





<meta name="viewport" content="width=device-width">
<title>graphhopper/config-example.yml at 0.13 ┬À graphhopper/graphhopper</title> <meta name="description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper"> <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub"> <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub"> <meta property="fb:app_id" content="1401488693436528">
<meta name="twitter:image:src" content="https://repository-images.githubusercontent.com/3480666/ab93f880-d9ff-11e9-80cb-e7ef95dbcd84" /><meta name="twitter:site" content="@github" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content="graphhopper/graphhopper" /><meta name="twitter:description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper" /> <meta property="og:image" content="https://repository-images.githubusercontent.com/3480666/ab93f880-d9ff-11e9-80cb-e7ef95dbcd84" /><meta property="og:site_name" content="GitHub" /><meta property="og:type" content="object" /><meta property="og:title" content="graphhopper/graphhopper" /><meta property="og:url" content="https://github.com/graphhopper/graphhopper" /><meta property="og:description" content="An open source routing engine. Use it as Java library or server. With OpenStreetMap. - graphhopper/graphhopper" />
<link rel="assets" href="https://github.githubassets.com/"> <link rel="web-socket" href="wss://live.github.com/_sockets/VjI6NTAxNjk3MjU5OjIyNjk1MWJkMTdkZTZhYTQyNWUxYzI1OWVkOGIwNmY0ZjkwZTM5NzM4ZTY2MGUwYWJmMzdhZTM5NWZjNzE4NDk=--fa92bdeaa5ee8e33417f191fc0eba88a12857fdb"> <link rel="sudo-modal" href="/sessions/sudo_modal">
<meta name="request-id" content="17F2:1C90:22ACB4:330C47:5E545EC3" data-pjax-transient="true" /><meta name="html-safe-nonce" content="cdc91887cc8701d96bba0188a81d4d41cdf3a4f8" data-pjax-transient="true" /><meta name="visitor-payload" content="eyJyZWZlcnJlciI6Imh0dHBzOi8vZ2l0aHViLmNvbS9ncmFwaGhvcHBlci9ncmFwaGhvcHBlci9pc3N1ZXMvMTkyNSIsInJlcXVlc3RfaWQiOiIxN0YyOjFDOTA6MjJBQ0I0OjMzMEM0Nzo1RTU0NUVDMyIsInZpc2l0b3JfaWQiOiIzOTgxMjUyODcwNDE4NTYyNzQ4IiwicmVnaW9uX2VkZ2UiOiJhbXMiLCJyZWdpb25fcmVuZGVyIjoiaWFkIn0=" data-pjax-transient="true" /><meta name="visitor-hmac" content="d606b198799a1c4927a59cc3bdb178bb353227e36ecc2805dbe8145b8093e6b8" data-pjax-transient="true" />


<meta name="github-keyboard-shortcuts" content="repository,source-code" data-pjax-transient="true" />


<meta name="selected-link" value="repo_source" data-pjax-transient>
<meta name="google-site-verification" content="KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU"> <meta name="google-site-verification" content="ZzhVyEFwb7w3e0-uOTltm8Jsck2F5StVihD0exw2fsA"> <meta name="google-site-verification" content="GXs5KoUUkNCoaAZn7wPN-t01Pywp9M3sEjnt_3_ZWPc">
<meta name="octolytics-host" content="collector.githubapp.com" /><meta name="octolytics-app-id" content="github" /><meta name="octolytics-event-url" content="https://collector.githubapp.com/github-external/browser_event" /><meta name="octolytics-dimension-ga_id" content="" class="js-octo-ga-id" /><meta name="octolytics-actor-id" content="47046040" /><meta name="octolytics-actor-login" content="feiercrack" /><meta name="octolytics-actor-hash" content="fd8ae89a9b495f81ce4c831de99898cb5eb79689e9bd54d6157b2dbb59ae9562" /> <meta name="analytics-location" content="/&lt;user-name&gt;/&lt;repo-name&gt;/blob/show" data-pjax-transient="true" />


<meta name="google-analytics" content="UA-3769691-2">
<meta class="js-ga-set" name="userId" content="7675ec213c7269ffaab9de6fa08aec67">
<meta class="js-ga-set" name="dimension1" content="Logged In">




<meta name="hostname" content="github.com"> <meta name="user-login" content="feiercrack">
<meta name="expected-hostname" content="github.com">
<meta name="js-proxy-site-detection-payload" content="OGNjNWQ5MGNhODJkZGQzYmQ5YjU0ODk2ZGQ4OGM3ODZhNTQzNDc1ZTQxMGNmZWUyNzgyYmZiNTBlZjc2ZmJmOXx7InJlbW90ZV9hZGRyZXNzIjoiODkuMjQ2LjEyMS4yMiIsInJlcXVlc3RfaWQiOiIxN0YyOjFDOTA6MjJBQ0I0OjMzMEM0Nzo1RTU0NUVDMyIsInRpbWVzdGFtcCI6MTU4MjU4NzYxOSwiaG9zdCI6ImdpdGh1Yi5jb20ifQ==">
<meta name="enabled-features" content="MARKETPLACE_FEATURED_BLOG_POSTS,MARKETPLACE_INVOICED_BILLING,MARKETPLACE_SOCIAL_PROOF_CUSTOMERS,MARKETPLACE_TRENDING_SOCIAL_PROOF,MARKETPLACE_RECOMMENDATIONS,MARKETPLACE_PENDING_INSTALLATIONS,RELATED_ISSUES,GHE_CLOUD_TRIAL">
<meta http-equiv="x-pjax-version" content="8310d593c1cc38b86be83242de7e6f3f">

<link href="https://github.com/graphhopper/graphhopper/commits/0.13.atom" rel="alternate" title="Recent Commits to graphhopper:0.13" type="application/atom+xml">
<meta name="go-import" content="github.com/graphhopper/graphhopper git https://github.com/graphhopper/graphhopper.git">
<meta name="octolytics-dimension-user_id" content="2264498" /><meta name="octolytics-dimension-user_login" content="graphhopper" /><meta name="octolytics-dimension-repository_id" content="3480666" /><meta name="octolytics-dimension-repository_nwo" content="graphhopper/graphhopper" /><meta name="octolytics-dimension-repository_public" content="true" /><meta name="octolytics-dimension-repository_is_fork" content="false" /><meta name="octolytics-dimension-repository_network_root_id" content="3480666" /><meta name="octolytics-dimension-repository_network_root_nwo" content="graphhopper/graphhopper" /><meta name="octolytics-dimension-repository_explore_github_marketplace_ci_cta_shown" content="false" />

<link rel="canonical" href="https://github.com/graphhopper/graphhopper/blob/0.13/config-example.yml" data-pjax-transient>

<meta name="browser-stats-url" content="https://api.github.com/_private/browser/stats">
<meta name="browser-errors-url" content="https://api.github.com/_private/browser/errors">
<link rel="mask-icon" href="https://github.githubassets.com/pinned-octocat.svg" color="#000000"> <link rel="icon" type="image/x-icon" class="js-site-favicon" href="https://github.githubassets.com/favicon.ico">
<meta name="theme-color" content="#1e2327">

<link rel="manifest" href="/manifest.json" crossOrigin="use-credentials">
</head>
<body class="logged-in env-production page-responsive page-blob">

<div class="position-relative js-header-wrapper "> <a href="#start-of-content" tabindex="1" class="p-3 bg-blue text-white show-on-focus js-skip-to-content">Skip to content</a> <span class="Progress progress-pjax-loader position-fixed width-full js-pjax-loader-bar"> <span class="progress-pjax-loader-bar top-0 left-0" style="width')
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
        ... 6 more

**Comment by feiercrack** [comment]
java -Ddw.graphhopper.datareader.file=berlin-latest.osm.pbf -jar graphhopper-web-0.13.0.jar server config-example.yml
java.lang.IllegalArgumentException: Unable to override graphhopper.datareader.file; it's not a valid path.
        at io.dropwizard.configuration.BaseConfigurationFactory.addOverride(BaseConfigurationFactory.java:169)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:122)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:34)

**Comment by feiercrack** [comment]
..dont understand..
