### ISSUE TITLE
Rename ProfileConfig into Profile and more refactorings

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2016]
See discussion: https://github.com/graphhopper/graphhopper/pull/1841#issuecomment-618969276

 - [x] ProfileConfig -> Profile
 - [x] move classes of `routing.profile` package into something storage related like `com.graphhopper.storage.ev`?
 - [x] something else like in #583 ? (or close that)

**Comment by easbar** [comment]
`ProfileConfig` -> `Profile` seems obvious, but then we should do `CH/LMProfileConfig` -> `CH/LMProfile` as well. `CH/LMProfile(Config)` aren't really 'profiles', but merely 'references' indicating that there should be preparations for the according profiles, but I do not have a much better idea atm. Only problem is that `CH/LMProfile` already exist. These two classes aren't really really related to the `Profile(Config)` either and they are more or less only used to carry some parameters and objects (like the `Weighting`) for the preparations. They might be refactored away entirely so they should not be a reason not to rename `CH/LMProfileConfig` to `CH/LMProfile`. Since it is not entirely clear what the purpose of (the current) `CH/LMProfile` classes is its hard to give them a name, maybe we just call them `CH/LMConfig`? So how about:

`ProfileConfig` -> `Profile`
`CH/LMProfile` -> `CH/LMConfig`
`CH/LMProfileConfig` -> `CH/LMProfile`

And for `2.0` we will probably remove `CH/LMConfig`...

**Comment by karussell** [comment]
> So how about

Yes, sounds good!

And should we seek for a better package name than `com.graphhopper.storage.ev`?

And #583 I would just close for now. (flag encoder will be resolved into some encoded value collections and algorithms subpackage is not worth it as mostly all classes in com.graphhopper.routing are algorithm related)

**Comment by easbar** [comment]
I did the renaming in this and the following commits: 90fac00ff2896a55f2cb6dd6b0c3cf4b8124fbb0 Lots of trivial changes... I hope the single commits make it a bit easier to update other branches :see_no_evil:

**Comment by karussell** [comment]
Have moved profiles to ev: https://github.com/graphhopper/graphhopper/compare/refactor_ev
Will see how much work this downstream is.

**Comment by easbar** [comment]
Maybe now is a good time for #1147 as well? `PathWrapper`->`ResponsePath`? :)

**Comment by karussell** [comment]
Yes :+1:

**Comment by karussell** [comment]
> Maybe now is a good time for #1147 as well? PathWrapper->ResponsePath? :)

I just noticed that SPTEntry is located at com.graphhopper.storage. Should we move it to com.graphhopper.routing. (maybe move also RoutingCH* class to com.graphhopper.routing.ch too?)

**Comment by easbar** [comment]
Honestly, I do not see much value in maintaining an elaborate (sub) folder structure unless it is about Java package privacy. But yes `SPTEntry` (and `ShortcutUnpacker`) certainly seem to not belong into storage).

**Comment by karussell** [comment]
:+1: 

> But yes, SPTEntry (and ShortcutUnpacker) certainly seem to not belong into storage).

Ok, will do this (only).
