### ISSUE TITLE
alternative route has detour for turn_costs=true

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2101]
For [this route](https://graphhopper.com/maps/?point=52.515803%2C13.377228&point=52.581148%2C13.476791&algorithm=alternative_route&turn_costs=true) there is a strange detour circle in the middle which disappears for turn_costs=false.

![image](https://user-images.githubusercontent.com/129644/88821910-7fbad500-d1c3-11ea-81af-cdc7a04d3916.png)

**Comment by michaz** [comment]
Ahhh, right. We need to concatenate "edge-based paths" properly.

Suppose we have a non-shortest candidate path s----u-v-w----t. Now we want a concatenation of two shortest paths via v. In node-based search, we take concat(s->v, v->t). In edge-based, we were taking concat(s->u-v, v-w->t). But that can be an ugly path (see above), because maybe from v-w we need to get back via u-v again.

Instead, we want concat(s->u-v, u-v->t). Concatenating "by edge", of course. (Removing the duplicate u-v edge.)
