### ISSUE TITLE
Add ability for restart of graphhopper instance remotely for unattended graph updates on servers

### ISSUE THREAD

**Issue by MarkCupitt** [graphhopper/graphhopper#211]
To help with periodic updates of the graph, it would be very useful to be able to trigger a restart of graphhopper by writing a semaphore file or via the api using curl or similar.

Use case would be in unattended graph updating on servers. Rather than bring graphhopper down and waiting wile the new graph was built, the rebuilding could be done in another Instance of graphhopper. When the graph creation was complete, the main instance could be brought down, the config file changed to point to the directory with the new graph and then the main instance could be restarted. resulting in minimal downtime on the service.

See also issue #112 re running multiple instances of Graphhopper

**Comment by HarelM** [comment]
Can the following be implemented?
http://www.randomactsofsentience.com/2012/01/stopping-andor-restarting-embedded.html
It uses the jetty infrastructure and the code is relatively simple.
I can submit a pull request if needed, but I think someone who know this area better and the jetty infra should do it as I have no means to understand if the code I linked to is any good...

**Comment by michaz** [comment]
It seems to me that this should be done from the outside. Or from the inside. But not on that level.

I mean, either GraphHopper gets a service API with which you can tell it to reload its Graph.
Or you stop and restart the GraphHopper executable, i.e. the JVM, with outside infrastructure (a container, a thing which controls daemons, etc.).

This here seems strangely in-between to me.

**Comment by HarelM** [comment]
I can't argue with your logic, however consider my case:
I'm running GH as a Windows service, the only interaction I have with this service is through http requests.
In order to restart the server I'll need to restart the Windows service which requires elevated permission, which I rather give of possible.
So I need a http command to restart the server in order to use the new cache I created.

**Comment by karussell** [comment]
@HarelM if we would implement this (at all) I agree with @michaz and this way seems to be too jetty specific and not useful if used elsewhere. Also why can't you create a crontab-alike entry which checks if a new graph is available and then restart the GH service? No external access would be necessary or how are you triggering the creation of the new graph cache?

**Comment by HarelM** [comment]
Currently, I'm using a command line java process to create a new cache in a new folder:
```java -cp \"*\" com.graphhopper.tools.Import config=config-example.properties datareader.file={osmFileFullPath} graph.location={GH_NEW_CACHE_FOLDER}```
Then I stop the GH server, switch between the cache folders and load the GH server again.
However, this requires admin permissions since the GH server java process is hosted as a windows service, which as I said I would like to avoid.
If you have a better method of doing so I open to suggestions.
This is currently the best approach we found to reduce the time the GH server is down for updates.
Note that this is a windows server and I'm writing code in C# and not in java (hence the need for external http requests)...

**Comment by HarelM** [comment]
Well, a better approach for me would be to send an http request to create a new cache, recive the new cache id and send another http request to switch between graphs/caches.
And the delete the old cache, again from http. This way I won't need to run any java process besides loading the server once.
This also requires the ability to get current graphs/caches so when the server is running I can query which graph is the "current" one.

**Comment by HarelM** [comment]
I think I'm over complicating this.
When loading the GH server I'm giving a file name for OSM database as a parameter.
My use case is that when this file changes, I need the GH server to update with minimal downtime.
One possible solution would be to use a file watcher and when this file changes create a new graph and delete the current graph once the operation is finished (although this leaves the cache parameter weird since the new graph won't know where to write its cache).
A second possible solution will be to call a HTTP method to signal the server the pbf file changes (similar to the above but doesn't require a file watcher, same issue with cache parameter).
I'll have some free times on my hands next week if you want to direct me to the location in the code assuming we agree on the approach I'll be able to contribute.

**Comment by karussell** [comment]
Every new feature deserves maintenance from us. Also it introduces security related concerns that needs thoughts. Also this restart often is coupled to trigger a change in the config of the load balancer (to reduce downtime to 0) and so forth. I'm currently more convinced to have this in a separate repo and we would be happy to link to it.

**Comment by HarelM** [comment]
I think this is very basic, I'm not sure I understand how this was not implemented already as I can't image a production server that doesn't need this. I don't think it has a place in another repository/code base.
It's true that you'll need to maintain this, but I don't think it should be a big effort.

**Comment by michaz** [comment]
The current design is that the graph is loaded at startup time. I think that's a defendable decision. Everything needs to be assigned some scope, and the most common ones are Singleton, Session and Request. This here is Singleton. 

So if one requires a new graph, they can restart. For restarting a service, use whatever your environment provides. I don't know Windows well, but there should be tools for that. The permission thing is really an administrative issue and should not directly lead to code changes.

**Comment by HarelM** [comment]
@michaz I understand your point in general.
My perspective is different, If you'd offer your code as a jar file that you can only use with Java and you'd need to write the service around it to support requests I would have no case.
But you decided not to.
When you decided to facilitate for HTTP requests it means that who ever uses this code doesn't need to write anything in Java theoretically, all a client needs to do is be able to send HTTP requests, which I think is a great solution to cross platform and cross languages (since every language has an http client).
My reference here which I also need in my production server and feel like they nailed the subject is Elastic Search.
Their API fully supports HTTP, including everything.
Since I use both I can compare and there was no need for me to open an issue there since they support everything I need from HTTP without writing a single line of Java code. They are hosted as a window service much like I host graph hopper and I don't need permissions since I don't need to bring it down.

P.S. The equivalent of a windows service in Linux is a daemon as far as I can tell, and in order to restart it you'll need elevated permissions (Don't take my word for it since I'm not a Linux expert) but if I'm correct this problem is not windows specific... The reason for creating a daemon is so that if the server restarts for some reason GH service will be available.

**Comment by karussell** [comment]
> Their API fully supports HTTP, including everything.

Their API also supports distributed requests, load balancing and much more and btw: they have hundreds of engineers ... so in theory it is nice to compare this to GH but in praxis we have to cut features somehow to concentrate maintenance on the important parts.

We are happy to link to your proposed changes from the docs and/or here. BTW: it is quite easy to embed the GHServer class in customized java code.

> Since I use both I can compare

We are happy ES users too and we can compare too ;)

**Comment by boldtrn** [comment]
Setting up periodic updates with bash scripts, crontab, etc might work well enough for Linux, but I can understand that this is seriously painful to do for Windows. So I understand why you are looking for an easy way to manage your instance on Windows @HarelM.

> 1.) either GraphHopper gets a service API with which you can tell it to reload its Graph.

Actually I kind of like this idea. So we could provide an `/admin` endpoint for this, that has to be protected somehow (password, IP Blacklist, JWT, ...). The endpoint would allow to perform certain management tasks, like loading a new graph file from the file system. This would make orchestrating a couple of graphhopper instances easy. 

For loading a new graph file I would think that we might need to re-run parts of the `DefaultModule#configure()` method. This would allow reloading the graph file with (almost?) zero downtime.

So from my point of view, we need a couple of good use-cases here to justify the development of something like this. But this is not really part of this issue, anyway :). 

The biggest benefit I see is when managing a lot of GH instances. You might have a load balancer. You might have lots of services around it. Here a couple of ideas, what you could do:

- Reloading graph files from the load balancer, so the load balancer could disable a routing server, reload the graph file and re-enable the routing server (not sure if this should be the responsibility of the load balancer)
- Fixing a broken routing server. So for some reason a server hung up, the load balancer marks it as unhealthy. Now the load balancer could simply restart the unhealthy server.
- Managing the config of a server from the load balancer. So maybe you want to remotely change the config of the routing server, you could simply do this from the load balancer (I have no idea, why I would want to do this, but, why not).

**Comment by karussell** [comment]
> Actually I kind of like this idea. 

Again, I like the idea as well, but we should first of all concentrate on the many more important non-service features that we have already on the list for years. And this feature is not just adding a new endpoint, security-wise I don't like to have without **proper** thoughts and testing.

**Comment by boldtrn** [comment]
> Again, I like the idea as well, but we should first of all concentrate on the many more important non-service features that we have already on the list for years.

I am 100% with you on this :) I was just thinking about the possibilities.

**Comment by HarelM** [comment]
I'm revisiting this topic again as I'm working on improving the downtime of the OSM updates on my server.
Here's another thought which might require less code and be more in-sync with how it's built right now:
1. Allow creating the GH server without a file (just loading it so it can wait for requests)
2. Add a HTTP API call to send an OSM file to the server - once the file is received a temporary cache/graph is created. when the creation is complete and graphs are switched.
This way the server is always up - no restart, no jetty specific code, what do you think?
I can work on it and create a pull request, I just need some guidance where to start.

**Comment by HarelM** [comment]
After further looking in the code here's what I came up with (Inputs are very welcome):
1. Allow the possibility to create the graph lazily:
  1.1 Add a configuration flag: `graph.lazy_load`, `false` by default, to facilitate for such option.
  1.2 The server is assuming there's a ready graph storage (BTW this is not an interface which makes things harder) - solution: create an interface for `Graph` and `GraphStorage` and create a class `EmptyStorage` which doesn't do much except facilitate for lazy loading (This is not my preferred solution but the code assumes the storage can't be null due to injection).
2. Add `RebuildServlet` for the address of `/rebuild` which accepts an OSM file in the payload, will load and import using the original command line arguments, once the storage is created use `setGraphHopperStorage` to update it on the original instance.
Am I in the right direction? 
I thought about adding a method to `GraphHopper` to facilitate for rebuild but I saw that the state is in a private member called `fullyLoaded` and I'll have a hard time changing that logic, I think...

**Comment by HarelM** [comment]
Added a discussion on this issue in the forum to get some help with the existing code:
https://discuss.graphhopper.com/t/rebuildservlet-design-review-and-code-queries/2009

**Comment by HarelM** [comment]
@karussell I would love your input on this, I'm at the final stages of implementation and it just doesn't feel 100% right.
What I've done so far:
RebuildServlet is calling GraphHopper newly written rebuild function which receives a graph that was created in a different location, closes the current graph and uses the new location instead.
The code is basically doing what it should, it just feels a bit hacky. I'll try and write some tests and see if I can make sure everything is covered. Should I commit and create a pull request for review?
I really need a feedback here...

**Comment by karussell** [comment]
I still do not understand why we need to change the core functionality to just reload the graph. IMO you could easily add a servlet, create a custom server to include this servlet (see eg. the map matching web module where we customize the GHServer) and then do the graph reload. This way we avoid to have to maintain it in the core (I think we are not yet there to include service functionality that introduce security questions and much more complexity) and it should be still easy on your side

**Comment by HarelM** [comment]
I can't seem to be making my point I guess.
The fact is - not everyone is writing in Java (Imperfect world, I know...).
I have a server which hosts GraphHopper as a process, the rest of the code is written in C#.
I do not want to write proprietary Java code only for this feature (Graph rebuild) since I believe it should be a part of GraphHopper capabilities - I think everyone that uses a system that updates and is not static would probably need this at some point.
Writing the code anywhere else beside in GH requires to know the internals of how GH works and creates an unhealthy coupling, IMHO. I tried to do it implement it a few times in other places and it just felt wrong.
The only functionality which I currently think is missing is this rebuild and facilitate it though HTTP is the only true cross-language solution.
The code I added is mainly focused in the `RebuildGraphServlet` but requires some minor changes in the core.
I haven't changed any tests and they all pass which might indicate the changes are truly minor also in terms of maintenance.
I really think others may find this piece of code helpful and I'll gladly spend a few more hours improving this so it can be merged here.

**Comment by HarelM** [comment]
Here's the relevant commit BTW:
https://github.com/IsraelHikingMap/graphhopper/commit/60683a6908a8879ca3e529daeda7d975e2990dab
The only thing that I'm not OK with is the `public LocationIndex getLocationIndex()` method which is used with injection to `NearestServlet` and does not allow null.
I believe a better solution for this will be to add `LocationIndex` to `GraphHopperAPI` as a property so that it can be changed after the graph is loaded the first time and there will be no need to inject it.
This is currently the only issue I see with the current implementation, but I'm very new to this code base so I might be way off. thoughts are very very welcome :-).

**Comment by michaz** [comment]
My new thoughts are still my old thoughts: 

The current architecture is (mostly) based on the assumption that the Graph is immutable. If you want a new Graph, stop and restart the service. It's what _we_ do on graphhopper.com! If you can't do this merely because you don't have admin access to the machine, I suggest you find some way to virtualize the server, run it in a container, or something.

> I believe a better solution for this will be to add LocationIndex to GraphHopperAPI as a property so that it can be changed after the graph is loaded the first time and there will be no need to inject it.

No. We're moving into exactly the opposite direction, where dependecies are injected at creation and are final from then on. When X depends on Y (or even _creates_ it like in this case), and you need an X with a new Y, the least-messy solution is to create a new X with a new Y, not change the Y under the X's feet. Except when X and Y were designed from the beginning to be like that, and there are naturally many Ys within the life-cycle of the X. This isn't the case here.

Work-arounds for the administrative problem of not being able to restart a server do not belong into the code-base.

**Comment by HarelM** [comment]
@michaz Thanks for your response.
It's very hard to convey an architecture discussion over a thread and not in person but I'll try to make my point never-the-less.
I have written such administrative service which shuts-down GH server and does the update. In the middle of writing it I noticed how deeply I'm coupled with how GH work (cache location, file location, can't do it from remote, etc...) and the more code I wrote the less right the solution felt.
I then stopped for a second and tried to solve this without assuming anything and the solution I ended up is what I committed. I believe this is the correct solution to the problem in terms of coupling and the way I perceive a client-server architecture when the server is always up.

Regarding what you wrote:
1. GraphHopper the class in terms of API is far from being immutable as it has public methods such as change location, set graphhopper storage, load, loar or import, etc... which makes it mutable, although some methods have checks in them, the API itself is not by definition an API for immutable class.
2. The Servlet API exposes changes method, this is not drastically different in term of API (I know it's different in term of the actual code though but I don't think it should guide this decision). 
3. LocationIndex is a part of the graph and shouldn't really exists on its own if I understand its creation flow, I might be missing something though, therefore I thought that adding it to the GraghHopperAPI interface would be more correct - meaning when you want to use location index you have to have an instance of a graph and you ask it for a location and not separate its existence by injecting it on its own.

I hope I'm making some sense, feel free to look at the code changes I made and let me know if this truly moves the code in what you define as the "wrong direction".

**Comment by HarelM** [comment]
You probably won't like the changes I made, but I didn't like the casting that I added and the one that was already there.
I added a few methods to GraphHopperAPI to support the required changes (and also to remove the casting).
All tests pass including the test I added.
Let me know if you are interested in pulling this in and I'll create a pull request.

**Comment by HarelM** [comment]
Unfortunately I spoken too soon. after rebuild I'm getting the following error when sending a route request, any thought where to look for the issue? it's probably a variable that wasn't initialized because if I close the process and open it again the graph is working as expected.
```
2017-06-11 21:39:15,436 [qtp510063093-43] ERROR com.graphhopper.storage.RAMDataAccess - nodes_ch_fastest_foot, segments:0, bufIndex:1, bytePos:1697720, segPower:20
2017-06-11 21:39:15,442 [qtp510063093-43] WARN  org.eclipse.jetty.server.HttpChannel - /route
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:208)
        at com.graphhopper.storage.CHGraphImpl.getLevel(CHGraphImpl.java:144)
        at com.graphhopper.routing.util.LevelEdgeFilter.accept(LevelEdgeFilter.java:51)
        at com.graphhopper.routing.AbstractRoutingAlgorithm.accept(AbstractRoutingAlgorithm.java:79)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdges(DijkstraBidirectionRef.java:164)
        at com.graphhopper.routing.DijkstraBidirectionRef.fillEdgesFrom(DijkstraBidirectionRef.java:132)
        at com.graphhopper.routing.AbstractBidirAlgo.runAlgo(AbstractBidirAlgo.java:68)
        at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:61)
        at com.graphhopper.routing.AbstractRoutingAlgorithm.calcPaths(AbstractRoutingAlgorithm.java:116)
        at com.graphhopper.routing.template.ViaRoutingTemplate.calcPaths(ViaRoutingTemplate.java:115)
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1054)
        at com.graphhopper.GraphHopper.route(GraphHopper.java:939)
        at com.graphhopper.http.GraphHopperServlet.doGet(GraphHopperServlet.java:142)
```

**Comment by HarelM** [comment]
OK, diving deeper... The instance of `PrepareContractionHierarchies` should not have been used.
This is due to the fact that `CHAlgoFactoryDecorator` is keeping a list of `PrepareContractionHierarchies`.
IMHO I don't think a factory should have a state, but clearing the list when calling `close` on `GraphHopper` solves the issue and rebuild is now working without exceptions (At least the tests I made).

**Comment by HarelM** [comment]
I still believe a routing server should always be up and should handle updates without the need to be restarted or swapped.
Having said that, I was unable to convince this respectful forum that what I wrote should be pulled in and now my code had diverged from this code base. :-(
Below is my new solution that uses docker, extremely hackish in my point of view, but I guess this is what is the advised to do...
1. A docker container and code that creates the graph called `docker-compose-gh-rebuild.yml`:
```yml
version: '3.4'

services:
  graphhopper-rebuild:
    image: graphhopper/graphhopper
    container_name: graphhopper-rebuild
    volumes:
      - ./data:/data:rw
      - ./gh-config.yml:/data/gh-config.yml
    entrypoint: ./graphhopper.sh
    command: import asia_israel-and-palestine.pbf -c /data/gh-config.yml -fd -o /data/default-gh/
```
2. a container that is almost always running for the web api at port 8989:
```yml
version: '3.4'

services:
  graphhopper:
    image: graphhopper/graphhopper
    container_name: graphhopper
    volumes:
      - ghdata:/data:rw
      - ./gh-config.yml:/data/gh-config.yml
    ports:
      - 8989:8989
    command: -i - -c /data/gh-config.yml -o /data/default-gh/
    restart: always
volumes:
  ghdata:
    driver: local
```
3. A script to swap the cache (the name of the volume is generated according to current dir, but can be assigned before starting this procedure):
```bash
docker rm graphhopper-rebuild
rmdir -force data/default-gh
docker-compose -f ./docker-compose-gh-rebuild.yml up
docker container create --name dummy -v ghdata:/root hello-world
docker-compose stop graphhopper
docker cp ./data/default-gh/ dummy:/root/default-gh/
docker rm dummy
docker-compose start graphhopper
```

Feel free to close this issue, no need to keep it open...
