### ISSUE TITLE
LoctionIndexTree.query doesn't visit all nodes

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper#2213]
See failing ignored test `LocationIndexTreeTest.testBoundingBoxQuery2`.

I thought maybe it isn't even meant to visit all nodes, but only all nodes with edges. But that isn't what's happening, either.

**Comment by karussell** [comment]
Yeah, something is wrong here.

The `LocationIndex.Visitor` is indeed too low level and only returns stored nodes and not all nodes (on purpose, but we should document this). But the `EdgeVisitor` should work as intended and yet it returns a very different node count (102 vs. 68). The best workaround at the moment seems to be:

```java
EdgeExplorer edgeExplorer = graph.createEdgeExplorer();
index.query(graph.getBounds(), new LocationIndex.Visitor() {
    @Override
    public void onNode(int nodeId) {
        EdgeIterator iter = edgeExplorer.setBaseNode(nodeId);
        while (iter.next()) {
            set.add(iter.getBaseNode());
            set.add(iter.getAdjNode());
        }
    }
});
```

But even here there is a mismatch (102 vs. 98).

**Comment by michaz** [comment]
Thanks for clarifying! I'll test again and possibly "tighten" it a bit. Main thing is that I know what is _supposed_ to come out there. I'll just ask again if I miss something. :-)

**Comment by karussell** [comment]
> I'll just ask again if I miss something. :-)

Sure :)

In theory the class is not that complicated :) ... but to keep memory usage low there are some tweaks:

 * every level of the "quad" tree could have 16 or 64 leafs instead of just 4 (this per-level leaf count is calculated up front). See #1485 for a rough visualization.
 * From the in-memory tree InMemConstructionIndex (Java objects) we call prepareIndex and store only integers (node IDs). For every cell that an edge crosses we store e.g. the base node of this edge into these crossed cells.
 * But I had [problems with "perfect" line rasterization](http://stackoverflow.com/q/24679963/194609) and so we sometimes store a node ID in a cell X which is not crossed by the edge and only near it. Although we can handle this when querying the index it would be nice to get rid of this inefficiency.
 * We do not have to store the boundaries of every cell somewhere. Instead we can calculate them implicit when we do the query as we know the size of the smallest cell (deltaLat, deltaLon)

And additionally it has to be very fast as our CH routing is so fast :)

**Comment by michaz** [comment]
> But I had problems with "perfect" line rasterization and so we sometimes store a node ID in a cell X which is not crossed by the edge and only near it.

I think we *do* only store a node ID in those cells X that are crossed by the edge. As we should, because that's the correct thing to do.
That's just not what Bresenham does. It's what Supercover does.
And it is what we do, except that the class is called Bresenham, not Supercover.

Correct?

http://eugen.dedu.free.fr/projects/bresenham/

**Comment by michaz** [comment]
Or is it the other way round, and we *do* use Bresenham, so we sometimes *don't* store a node ID in a cell X *even though* it is crossed by the edge, and we try to handle *that* during query?

**Comment by karussell** [comment]
Ah, ups, indeed. It was the other way around and we store the node IDs in **too few cells** and use bresenham. This is also the reason that for every location lookup we need to look at least into the 8 surrounding cells.

This supercover algorithm looks like the thing I was looking for - nice! After so many years you answered my question :)

**Comment by michaz** [comment]
> This supercover algorithm looks like the thing I was looking for - nice! After so many years you answered my question :)

Actually, that's from your comment in the class. :-D

**Comment by otbutz** [comment]
> but it didn't work in our case as it works with integer values and not decimals like required for lat+lon. 

Can't we scale the coordinates and apply the algorithm to their integer representation?

**Comment by karussell** [comment]
> Can't we scale the coordinates and apply the algorithm to their integer representation?

I tried this at that time without success for certain real world cases, also someone in the one answer tried to find a solution for this, but it also didn't work for me. 

> Actually, that's from your comment in the class. :-D You even give references etc.

Ah, ok :) ... hmmh, then I likely also tried it without success. I tried so many things at that time, because I was (and am) pretty sure there is a way and I dislike(d) this imprecision. But at the end the workaround via fetching also the "next cells" worked too good to invest more time.
