### ISSUE TITLE
remove graphhopper.sh

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2361]
See #2360

**Comment by HarelM** [comment]
Please let me know what's the best and easiest way to build the project from command line in case the `build` command will no longer be available (due to this feature).
See here:
https://github.com/IsraelHikingMap/graphhopper-docker-image-push/blob/aee63fc944ab061ad97a0a7d17fa40f3d0e2f626/Dockerfile#L9
From my point of view, if you could send a small PR it would be amazing :-)

**Comment by karussell** [comment]
If you want to build it from sources do:

 * get JVM: https://adoptopenjdk.net/
 * get maven: https://maven.apache.org/download.cgi
 * run `mvn clean install`

As you base your docker image on a maven derivative (it seems?) you should be able to skip the two commands and just run `mvn clean install`. 

If you want to just get the released jar you should just download it: https://github.com/graphhopper/graphhopper#installation

**Comment by HarelM** [comment]
OK, Thanks!
I'll update the script in the next few days and monitor that it works as expected.

**Comment by HarelM** [comment]
Isn't the right command to only build is the following:
`mvn --projects web -am -DskipTests=true package`? 
This is what's written in the graphhopper.sh now (I think), is this incorrect?

**Comment by karussell** [comment]
> -DskipTests=true 

If you build from master then skipping tests is a bit risky. The other options are not necessary. And `package` is included in `install` but `package` should be sufficient, yes.

**Comment by HarelM** [comment]
So where is the .jar is generated when running `install`? I ran `mvn clean install` and didn't find the jar files in the `./web/target/` folder.
Also I'm getting two files there, one that start with `original`.
I agree the tests should run.
Please let me know where I can find the file that I need in order to run everything...
I don't mind running mvn clean install...

**Comment by karussell** [comment]
Yes, it should be in: `web/target/` and is currently called `graphhopper-web-4.0-SNAPSHOT.jar` (42MB).

**Comment by HarelM** [comment]
OK. I think I made all the relevant changes in the docker related repository.
Please ping me when you create a pre-release or release tag so I can upgrade my docker related setup to see that it behaves well without this file.
