### ISSUE TITLE
Remove workarounds for missing jackson dependency in core

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2365]
With #2354 we finally have jackson available in core so we can get rid of a few warts like GraphHopperConfigMixIn or JSON handling in GraphHopperManaged

**Comment by easbar** [comment]
This is somewhat 'sketchy territory', because often it leads to the question what the core module really is about. For example should parsing `config.yml` (GraphHopperConfigMixIn) be part of the core? Or is this a feature of the 'webapp' (web-bundle)? Is the `GraphHopper` class an application in and of itself or is there only really one (web) application/server (which uses Dropwizard and config.yml as configuration?). 

I think I will start with this JsonFeatureCollection constructor parameter, because this is very similar to what we need for custom areas.

**Comment by michaz** [comment]
Thanks! Just want to say I appreciate *both* you going forward *and* your level of architectural caution here. ,-)

**Comment by easbar** [comment]
Yes, I think core should be 'allowed' to use Jackson to read GeoJSON (just generally), but e.g. the `GraphHopperConfigMixIn` that is solely used to read the `GraphHopperConfig` from `config.yml` is rather not a part of core.

**Comment by michaz** [comment]
Of course, most of that discussion would be conveniently over if the JRE just had JSON internally.
