### ISSUE TITLE
AbstractNonCHBidirAlgo: improve PriorityQueue handling

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper#2408]
We currently remove and readd modified SPTEntries(L163-165) within the loop in order to update their position in the queue:

https://github.com/graphhopper/graphhopper/blob/5e88f307701a47f9e7afddece135ab209542727a/core/src/main/java/com/graphhopper/routing/AbstractNonCHBidirAlgo.java#L146-L177

This is rather expensive as PriorityQueue.remove(Object) has a complexity of O(n), checking each element in the queue for equality.

We could mark those entries instead (e.g add them to a Set) and update the Queue after the loop has finished:

```java
Set<SPTEntry> modified = new HashSet<>();
while (iter.next()) {
        //...
        updateEntry(entry, iter.getEdge(), iter.getAdjNode(), origEdgeId, weight, currEdge, reverse);
        modified.add(entry);
        // ...
}
prioQueue.removeAll(modified);
prioQueue.addAll(modified);
```

**Comment by easbar** [comment]
Ok, I see `removeAll` is optimized for bulk removing multiple elements. `addAll` is just calling `add` for each element.
Did you try this yet? Btw another option is to set a 'removed' flag for the queue entries instead of actually removing them. The flagged entries are then rejected when they are polled from the queue. I think we tried this before, but not sure how much of a difference it made and maybe it is worth trying this again.

**Comment by karussell** [comment]
Could be interesting. See also #2092, #2107, #475 and #489.

**Comment by easbar** [comment]
I tried this here: 04011ef11e63fd165b90d5d95e07da4b64a8b003
Will post benchmarks when they are ready

**Comment by easbar** [comment]
Hm, unfortunately this is not faster and maybe even slightly slower, like 1.5ms vs 1.4ms. At least the way I implemented this. But maybe this can still be improved?

The strange thing I do not understand is that for non-CH my change yields a massive slow down, like 3.5s vs 0.1s. @otbutz you opened this issue for CH especially. Did you also experience that this tweak does not work for non-CH?

**Comment by otbutz** [comment]
I did not check it yet. Just noticed PriorityQueue.remove(Object) taking some noticeable amount of time.

**Comment by karussell** [comment]
> The strange thing I do not understand is that for non-CH my change yields a massive slow down, like 3.5s vs 0.1s.

The problem might be that PriorityQueue is extremely well tuned and hard to beat. OR that the bigger queue size is bad for iteration and polling OR that the Set makes the problems. Maybe you initialize the Set with 1000 or something or even use an ArrayList?

**Comment by otbutz** [comment]
I'd profile with JMC to really get the culprit here.

https://adoptopenjdk.net/jmc.html

**Comment by easbar** [comment]
I tried using an `ArrayList` instead of a `HashSet` for non-CH and this was much faster (around x2), but still much slower than master. For CH it was still around the same, so no real improvement compared to master. The issue with non-CH is that `removeAll` traverses all elements of the **queue** (not only the ones of the given Collection that shall be removed), so if the queue is large it takes a long time.

Feel free to profile this in more detail using JMC, and re-open this issue, but currently I do not feel like trying further in this direction. If we actually wanted to speed up CH we should rather think about not using the BaseGraph/CH hybrid we are using at the moment and re-labelling the nodes according to the CH level. This would easily improve speed by around a factor of two and probably more (but require more memory).
