### ISSUE TITLE
setAllowWrites(false) makes GraphHopper.load() fail even though no write access is needed.

### ISSUE THREAD

**Issue by oli0044** [graphhopper/graphhopper#2498]
**Describe the bug**
When setting `setAllowWrites(false)` for non-writable file systems the `GraphHopper.load()` function fails in the subfunction `prepareCH()` because `prepareCH()` requires write access, even when there are no CHProfiles to be prepared.

The prepareCH() function throws an `IllegalStateException("Writes are not allowed!")`.

**To Reproduce**

```
GraphHopperConfig config = new GraphHopperConfig(); // iniitalize parameter map
config.putObject("index.max_region_search", 8); // define more iterations to find the points more accurately
config.getProfiles().add(new Profile("car").setVehicle("car").setWeighting("fastest")); // add the profile
config.getCHProfiles().add(new CHProfile("car")); // set the rofile for speed mode

GraphHopper hopper = new GraphHopper().setGraphHopperLocation(distancesFolder.getAbsolutePath()) // set working directory
                                   .setPreciseIndexResolution(1000) // define higher resolution to find the points more accurately
                                   .init(config) // start graphhopper instance
                                   .setAllowWrites(false) // only read the file
                                   .setGraphHopperLocation(distancesFolder.getAbsolutePath());
hopper.load(); // load gaphhopper
```

**Expected behavior**
The `prepareCH()` function should not throw an `IllegalStateException("Writes are not allowed!")` if no CHProfile has to be prepared.

**System Information**

operating system: Ubuntu 20.04
JDK: java-11-openjdk-amd64
GraphHopper: current master branch

**Comment by oli0044** [comment]
See pull request #2499

**Comment by easbar** [comment]
Yes, I think this is a bug. But before we come up with a fix we need to clarify what this `isAllowedWrites` flag is even supposed to do. This part of GraphHopper needs an overhaul anyway, if you ask me. Related to: #1895.

So why should we `setAllowWrites(false)` when we call `load`? If we were **loading** why should we expect anything to be **written** and then disallow such writing? This sounds obvious, but actually you are right in a way, because the `load()` method **can** actually write. For LM (and since #2481 also for CH) **load** means: "load  the available preparations, but create the others when they are still missing". So it kind of makes sense to disallow writing when calling load, because a somewhat reasonable assumption would be that calling `setAllowWrites(false)` just before `load()` would mean that the loading will be done as usual, but this 'delta-import' feature was disabled. However, this would be a rather strange, not to say terrible, API for doing this.

The next thing is that 'creating' CH/LM preparations does not even necessarily mean that something is written to disk. The preparations could just as well be only created in memory and never be flushed to disk. This is complicated by the fact that the behavior is not the same depending on the `DAType`. For `MMAP` we always need to write to disk, while for `RAM` we can either not write to disk at all, or delay writing to disk until we call `flush()`. In the future I'd like to reduce this to two options only: 

1) We create something in memory with the intention to write it to disk **at some point**. In this case we should write a file or a dummy file to disk immediately, because for `MMAP` this is exactly what will happen and therefore the `DAType` abstraction will be a lot simpler if we just do the same for `RAM`.
2) We create something in memory without the intention to ever write it to disk (in-memory only). No files are written, no matter which `DAType` we use (for `MMAP` this option does not exist of course).

Therefore, I see the following usage patterns:

1) **clean import**: We run an import (OSM data is read, the graph, preparations etc. are written to some folder). If the folder or files already exist this is either an error or we allow overwriting the existing data using some `overwrite/force=true` flag that is disabled by default.
2) **pure load**: We load data from a given folder. If the folder does not exist it's an error. We load just the data that is there, without writing anything. It should not be necessary to 'replicate' the configuration we used for the import before. I.e. everything needed to load the data should be included in the data. E.g. it should not be required to specify the same encoded values that were imported in the configuration, because they were already written to disk anyway. However, there are other things we need to be able to configure. For example we might want to load some files using `RAM` even though they were imported using `MMAP`, or use the `MMAP` pre-loading feature (#2432) etc. So we should be able to configure the things that can be changed when loading data, but not be required to specify the things we can no longer change anyway. 
3) **partial load**: Given a folder and configuration we only load parts of that folder, like there are seven CH preparations and we only need to load two of them (and maybe next time we load three others). Otherwise we need to be able to use the same loading configuration options as in 2).
4) **delta import**: We should be able to add e.g. CH/LM preparations to an existing graph folder.
5) **import or load**: When we start the GH server we like to either load the existing data, or run the import first. This is probably the most tricky one, because it can be a combination of all of the above and it might not at all be obvious what is even supposed to happen in this case depending on the configuration and existing data. I am not 100% convinced we should actually allow this instead of just separating the 'import' step from the 'load/start server' step completely, but as we've always allowed this workflow it would probably be a rough thing to do to not allow it any longer. 

Ok, with this little background back to your issue. What did you want to achieve when you decided to `setAllowWrites(false)` and then call `load()`? To me it is not clear what this is supposed to mean, because a `load` method should not do any writes anyway. But it does... Did you want to disable the delta imports by setting `setAllowWrites(false)`. If yes, I agree there should be some way to do this, but it certainly should not be done using `setAllowWrites(false)`.  Does any of the five scenarios I listed above match your use-case?

**Comment by karussell** [comment]
> For MMAP we always need to write to disk

No, this is [not necessary](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/MMapDataAccess.java#L240).

This allowWrites option can e.g. be set to false when using it on a read-only filesystem or network filesystem (I think) or similar.

**Comment by easbar** [comment]
> No, this is not necessary. 

Ok, we don't always need to write to disk when using `MMAP`, but what I meant is that there always needs to be a file on disk to use `MMAP` (that at some point had to be written).

**Comment by karussell** [comment]
> I am trying to say: Trying to write on a read-only file system is a usage error and the usage should be changed.

Do you mean instead of the lower level "don't allow writes" the user should be able to specify "don't modify graph"?

**Comment by easbar** [comment]
> Do you mean instead of the lower level "don't allow writes" the user should be able to specify "don't modify graph"?

I think the user should be able to specify things like 'import', 'load' etc., see my list of five usage patterns above.

**Comment by oli0044** [comment]
@easbar yes **scenario 2** is my use case and the graph lies on a network device so that multiple graphhopper processes can use the same graph/saved data. That's why it is important for me to prevent any writes to the graph, so that the other processes are not interrupted.

If I'm not mistaken the `load()` function also writes a read lock file if `setAllowWrites(false)` is not set. 

So `setAllowWrites(false)` actually prevents writing to a read-only file system and without, the function the `load()` function would always try to write a lock file and fail and therefore GraphHopper would fail with a `RuntimeException("To avoid reading partial data we need to obtain the read lock but it failed. In " + ghLocation, lock.getObtainFailedReason());`

**Comment by oli0044** [comment]
Have you considered pull request #2499 as a temporary fix?

I agree, that the logic behind `setAllowWrites(false)` should be integrated properly in the different use cases/scenarios. However there are so many shared functions and subfunctions down the line of the different scenarios, that it seems a bit more complicated to prevent all write access in certain scenarios while allowing them in other scenarios.

The idea of a lock file for example is not a bad one in general, just not on a non-writable file system.

**Comment by michaz** [comment]
I think an incremental improvement (so my customer can load their contraction hierarchies on their read-only filesystem again) is to just remove the ensureWriteAccess().

This now means that in the case where the user said setAllowWrites(false) and there are CHs to build, this will now be violated.

But if the intention of this option was to let GraphHopper be well-behaved on an actual read-only file system (and it was!), that doesn't matter -- it will just hard-fail when it tries to write, and that is less often than now, where it will always fail, even if it doesn't actually want to write.

**Comment by michaz** [comment]
Do we even need `setAllowWrites`? (I think the more usual name would be `readOnly`, right?)

As @easbar says -- if we write or not should just follow from what the user is doing. If there's nothing to write, nothing will be written. No need for an extra doorstop to *forbid* writes on top of that.

**Comment by michaz** [comment]
Also: I'm aware it's not *clear* that this is the right metric, but the entire locking code seems to be among the oldest in the repository. 

Do we still think this is a problem our code should solve, or can we leave it to the user to make sure that a GraphHopper directory is first created _and then_ used if they want to use multiple GraphHopper processes?

Can't we just delete all of this?

**Comment by data-ux** [comment]
In my mind using multiple processes only makes sense if the graph is prepared beforehand, right?

**Comment by michaz** [comment]
Yes! And _technically_, file-based locks can help ensure that.

But my understanding is that, since locks are "cooperative" anyway (process 1 and process 2 only coordinate if both respect the locks), they are mostly useful when the application is *routinely* run in several processes on the same data directory.

**Just** as a safety so a user doesn't read from a directory where another (hypothetical!) process is still busy importing -- I don't think that's necessary, **because** it could just as well be that the user copies their data files in a script (like we do) and then the locking scheme fails anyway.

So I think we shouldn't do it.

**Comment by easbar** [comment]
Yes, I also think we could start with removing the lock file and `setAllowWrites` and maybe later think about supporting such multi-process use cases again. Right now we don't use it and I'm not sure if anybody does. The GraphHopper class and some of the related code is up for a bigger refactoring and probably it is easier to progress if we remove some of the code that is only used hypothetically. I think the allowWrites/lock file stuff belongs to this category. @karussell?

**Comment by karussell** [comment]
> "Don't use a data directory that you are still busy creating" is something the user should handle on their own.

I think we created the lock file mechanism to avoid accidentally running two import processes at the same time for the same graph-cache folder. Wouldn't this useful to have this protection or should we stop the import process if the graph-cache folder already exists?

**Comment by easbar** [comment]
> or should we just stop the import process if the graph-cache folder already exists?

That would not work because we support for example adding LM/CHs to an existing folder. If we want to protect against running two import processes at the same time we should probably either add a lock file on a lower level (when something is actually written, not when something high-level like `load` is called), or check if the files to be written (like `edges` for example) already exist.

**Comment by easbar** [comment]
I think our data files should **be** our lock files in this scenario. If an import starts and there is e.g. the `nodes` file already it should just crash. The files should just be created the moment we request a new DataAccess, just like we do (and have to do) for MMAP already. Then there is no need for a lock file and no need for the `HashMap` in Directory either.

Since we aren't there yet, maybe we can just create the lock file for the `import` command. The `server` command will crash upon its second invocation anyway, because the port will be used already.
