### ISSUE TITLE
Quickstart is outdated

### ISSUE THREAD

**Issue by jonas-db** [graphhopper/graphhopper#2501]
The readme seems outdated: https://github.com/graphhopper/graphhopper/blob/4.x/docs/core/quickstart-from-source.md#try-out

- It suggests to run `./graphhopper.sh -a web -i europe_germany_berlin.pbf`, yet there is no such .sh file:
shouldn't it be a jar file?
- It also requires an unspecified config.yml: `Program arguments: server config.yml`
should point to: https://github.com/graphhopper/graphhopper/blob/master/config-example.yml

**Comment by karussell** [comment]
Thanks for the report and trying out GraphHopper.

If you switch locally to 4.x there is still the graphhopper.sh file: https://github.com/graphhopper/graphhopper/tree/4.x

The problem is a bit that we would have to change this hidden line on every release:

> git checkout master # if you prefer a less moving branch you can use e.g. 3.x

The quickstart for the master branch is already adapted: https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md

**Comment by karussell** [comment]
Glad you got it working. Could you create a new topic in our forum for the other subject?
