### ISSUE TITLE
Download problem and route create problem

### ISSUE THREAD

**Issue by Daniele7777** [graphhopper/graphhopper#251]
Hi

I get 2 problems with Grapphopper.

When i start app, does not display a list of maps that can be download, it show a toast ask me if i am connected to internet. Second, if i try to create a route, it crash after red flag has been add to the map. the Logcat display "Call load or importOrLoad before routing"

**Comment by karussell** [comment]
I've provided a workaround 'AndroidDownloader' so that the HttpClient instead of the plain HttpUrlConnection is used. But I have no idea what the real cause is. As Android has lots of problems related to certification stuff I guess it related to this or the SSL3 fallback or something. It could be important to find the cause as it might be a security problem (not that problematic for this download but for other stuff it could get important) and maybe someone else could invest a bit more time into debugging the plain 'Downloader' for Android version 4.*

If this works for at least one other dev, I'll merge the branch or merge better suggestions :)

**Comment by karussell** [comment]
Ok, no feedback means all works ;) so merged it for now. Please try and report here if success or still problems

**Comment by devemux86** [comment]
I just tested it in KitKat and it works. :)

**Comment by karussell** [comment]
Thanks for the feedback! And nice that it works!

**Comment by devemux86** [comment]
It's worth noting this:
http://developer.android.com/about/versions/android-5.1.html#http

**Comment by karussell** [comment]
Thanks! Understandable, but now the problem is that we were already using URLConnection before in our Downloader class and this made the problems with HTTPS. (I guess the problems are due to some certificates and apache http was using a different set or something, I really dislike this Android diversity mess and the 'platform independence' Google introduced)

**Comment by karussell** [comment]
See [comment](https://github.com/graphhopper/graphhopper/issues/498#issuecomment-158333912) what probably really went wrong here.
