### ISSUE TITLE
Barrier edge leads to near-infinity value of average_speed 

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2636]
The problem is that the distance of these barriers is 0 (The point is a lift_gate: https://www.openstreetmap.org/node/9664334304 )

See https://discuss.graphhopper.com/t/wrong-average-speed/7411

Related #2620.

**Comment by otbutz** [comment]
Just a quick thought but can't we fix those values in a postprocessing step by replacing them with fitting values from adjacent edges?

**Comment by easbar** [comment]
I think @karussell meant the `average_speed` path detail here, which is not stored for each edge, because it depends on the weighting that is used. So it is calculated as `distance / weighting.calcEdgeMillis(edge)`, and since `calcEdgeMillis` is typically proportional to the distance (which is zero) we divide by some small number. But yes, maybe we could just use the resulting path detail value of some neighboring edge in this case. Or just do the same as we do when the distance is too small also when `calcEdgeMillis` is too small...
