### ISSUE TITLE
add "permit" as allowed access value

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2712]
[This ferry](https://www.openstreetmap.org/way/6529819) uses the unusual tagging motor_vehicle=permit. Should we support this only for ferries or as general access tag? What is the difference to "yes"?

**Comment by mprins** [comment]
> What is the difference to "yes"?

Essentially this means "no" (unless you have a permit), `motor_vehicle=permit` you need a permit to bring your car to the island.

**Comment by easbar** [comment]
Then what is the difference to "private"? Can anyone obtain a permit? Then it would be the same as "yes", because "yes" could still mean you have to buy a ticket (similar to a permit(?)). Or can only certain people obtain a permit? Then it would be the same as "private" (at least as far as GraphHopper is concerned(?)).

**Comment by mprins** [comment]
In case of Schiermonnikoog you can request a permit if you have residency on the island or if work/commerce requires a motor vehicle. There are quite some rules that apply to vehicles as well, all at the discretion of the municipality.

The permit is required for any motor vehicle (incl. moped/motorcycle/etc.) and is also needed for driving on the island.

As far as routing is concerned "private" would probably a good approximation
