### ISSUE TITLE
improve surface parser

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2751]
See [this discussion](https://discuss.graphhopper.com/t/concrete-surface-treated-as-other/7768) and:
https://www.openstreetmap.org/way/1077235613

https://wiki.openstreetmap.org/wiki/Tag:surface=concrete:plates

**Comment by otbutz** [comment]
These are also missing:

* [surface=pebblestone](https://taginfo.openstreetmap.org/tags/surface=pebblestone#overview) -> ?
* [surface=grass_paver](https://taginfo.openstreetmap.org/tags/surface=grass_paver#overview) -> `Surface.PAVING_STONES` / `Surface.DIRT` ?
* [surface=unhewn_cobblestone](https://taginfo.openstreetmap.org/tags/surface=unhewn_cobblestone#overview) -> `Surface.COBBLESTONE`

Pebblestone should probably get it's own value:

![image](https://user-images.githubusercontent.com/22315436/229835159-b523ad71-ba9f-4789-9586-6021f78f7ab0.png)

It's used quite a bit and i'm unsure if we should to treat it as impassable or at least avoided terrain for a few transportation types as these rocks might be quite large according to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag%3Asurface%3Dpebblestone). 

> Pebbles are stones rounded by waves or river flow. Typical size range from 2 to **8 cm**.

That would make them even worse than gravel roads in my opinion.

**Comment by otbutz** [comment]
I'm a little torn on grass pavers. Although they are obviously better than grass, I would still treat them as "Surface.GRASS" because on the one hand they can be overgrown and on the other hand they have to be treated differently in terms of accessibility.

**Comment by otbutz** [comment]
@ratrun as these are mostly cycling related, what's your opinion?

**Comment by ratrun** [comment]
Thanks for pointing me on these planned changes.

I counted the amount of surface values we currently support and my result is that 15 values are defined in the enum. Would it be possible to utilize a 16th value? 
The reason why I'm asking is because according to the [wiki](https://wiki.openstreetmap.org/wiki/Key:surface) and [taginfo](https://taginfo.openstreetmap.org/keys/surface#values) we are covering the most important values except for `metal` and `sett`. Your proposual is to map `metal` to `PAVED`, which I don't think is a good idea. Metal may become very slippery when it is wet and then you cannot treat it like `PAVED`. The same is true for `wood`. Therefore I would utilise the 16th value for both of these values and call it 'METAL_OR_WOOD'.

Or could we spend even 5 bits? In this case we could define the often used `sett`, `wood`, `metal`, and more.

If not then I agree with your proposual:

- `sett` -> `COBBLESTONE`
- `unhewn_cobblestone` -> `COBBLESTONE`
- `earth` -> `DIRT`
- `pebblestone` -> `GRAVEL`
- `grass_paver` -> `GRASS`

**Comment by otbutz** [comment]
I didn't change how we interpret most of them. This is the current logic:

https://github.com/graphhopper/graphhopper/blob/8ceab61325ac56416be88730db5168077fc64bcc/core/src/main/java/com/graphhopper/routing/util/parsers/OSMSurfaceParser.java#L43-L50

But I agree that it is probably worth increasing the granularity of our Surface enum. The fact that the average bikespeed parser uses this information is a good indicator that we need this level of detail:

https://github.com/graphhopper/graphhopper/blob/8ceab61325ac56416be88730db5168077fc64bcc/core/src/main/java/com/graphhopper/routing/util/parsers/BikeCommonAverageSpeedParser.java#L46-L71

**Comment by otbutz** [comment]
@karussell should we introduce new enum constants or map to existing ones?

**Comment by otbutz** [comment]
@ratrun @karussell i've updated my PR and added `Surface.WOOD`
