### ISSUE TITLE
Incorrect snapping for ferry routes. LocationIndex should know only start and end

### ISSUE THREAD

**Issue by DanySK** [graphhopper/graphhopper#322]
Hi all,
I rely on Graphhopper for simulating opportunistic networks of mobile devices in real-world setups. The project is called Alchemist and it is supported by University of Bologna. The high number of randomly displaced devices allowed me to spot some curious behaviour, that I was able to reproduce in the web version of Graphhopper: apparently, navigable lines are interpreted as legit foot path.

To reproduce, please visit this link:
https://graphhopper.com/maps/?point=51.502091%2C-0.123076&point=51.500435%2C-0.12225&vehicle=foot&elevation=true&layer=Lyrk

I guess that such behaviour is anomalous. I make widespread use of LocationIndex.findClosest() in order to be able to map possibly wrong devices position to plausible coordinates, but they often end up suggesting... swimming. This is one other example: https://graphhopper.com/maps/?point=51.500341%2C-0.122609&point=51.500408%2C-0.119519&vehicle=foot&elevation=true&layer=Lyrk

**Comment by karussell** [comment]
That is a ferry, not really swimming and not anomalous. In order to map sequential data points to edge ids you might be interested in our new [map matching component](https://github.com/graphhopper/map-matching)

But I see what you mean and maybe the route should not start directly on a ferry. Not sure.

**Comment by karussell** [comment]
See the corresponding [OSM layer](https://graphhopper.com/maps/?point=51.502091%2C-0.123076&point=51.500435%2C-0.12225&vehicle=foot&elevation=true&layer=OpenStreetMap) for a more detailed look of the ferry routes.

**Comment by DanySK** [comment]
Than you for your answer, I understand.

Unfortunately the (nicely powerful) map matching is not a viable work around in my case: I often need, for instance, to displace hypothetical network nodes on a real-world map, and in order to do that I use the method mentioned above. As you surely realise, this is disruptive if the simulated area comprises navigable water streams. I am currently working this around using bike paths, but is clearly sub optimal.

Anyway, apart from my very problems, which I believe should not be considered since graphhopper aims at a general navigator solution, it appears to me that:
* I agree with you that it makes little sense starting a route from a ferry. One problem here is that if you try to start to navigate from a bridge, even a little drift in GPS precision may lead to the suggestion of taking a ferry. I noted also that if ferries and bridges intersect, on intersection points some times a ferry is suggested as closer point.
* I also agree that ferries should not be mixed. More in general, they should not be considered as plain roads.
* Mixing ferries and walks inevitably makes route times mismatch reality (unless graphhopper is considering ferries timetables, which I guess it is not). I think that in case the ferry routes management is modified, this issue should also be considered.

**Comment by neiljp** [comment]
It seems to me that ferries are currently treated as 'paths' in the analysis. This is suggested to me partly due to the existence of routes such as the following:
https://graphhopper.com/maps/?point=51.501998%2C-0.123103&point=51.504562%2C-0.120656&vehicle=foot&locale=en-US&elevation=true&layer=OpenStreetMap

GH seems to really only work with the idea of 'highways' at the moment, ie. where one can move over the 'public' routes and essentially with no rights issues. Ferries (presumably) will cost money, have timetables, different speeds, as indicated above. For me, this indicates that rather than treating ferry journeys as paths (alone), the appropriate approach would be to work on using routes (osm relations).

Does anyone else agree?

**Comment by karussell** [comment]
> Does anyone else agree?

yes, introducing duplicate paths regarding the ferry routes would be necessary here too, or via 'turn restrictions'

**Comment by karussell** [comment]
This is now possible with snap preventions, e.g. https://graphhopper.com/maps/?point=51.502091%2C-0.123076&point=51.500435%2C-0.12225&vehicle=foot&snap_prevention=ferry
