### ISSUE TITLE
Improve finding the next instruction

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#335]
Search backward and forward to handle most cases when users going too far off the route. See discussion [on the mailing list](https://lists.openstreetmap.org/pipermail/graphhopper/2015-February/001658.html). Related to #331

**Comment by darek607** [comment]
There is another big issue with InstructionList find(). 
Look at this route: https://graphhopper.com/maps/?point=50.79834%2C19.113336&point=50.796659%2C19.110632&locale=pl-PL&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Lyrk
When the user is under viaduct, then it returns instruction that is higher (finish), because this method does not take into account the height. Is there any good workaround for this issue?

**Comment by karussell** [comment]
Interesting, and this is indeed a limitation. You could create a special EdgeFilter and check for similar elevation data or use [our map matching component](https://github.com/graphhopper/map-matching/) to further improve this process.

**Comment by karussell** [comment]
See #2250 and https://github.com/graphhopper/graphhopper-maps/issues/174
