### ISSUE TITLE
Bicycle/MTB routing should observe bicycle=yes on a barrier

### ISSUE THREAD

**Issue by arminus** [graphhopper/graphhopper#407]
Presently, a node with a tag barrier=kissing_gate and bicycle=yes blocks bicycle or mtb routing through that node. 

IMHO, a tag bicycle=yes should override any barrier on a node (same goes for stile, turnstile, etc). Plus, the bicycle=yes tag should allow routing for all "bike-types".

**Comment by karussell** [comment]
@NopMap and @ratrun can you confirm this change proposal?

**Comment by ratrun** [comment]
I fully support the propsual. It makes sense, especially for vehicle type mountainbike. After having read the definition for a kissing_gate barrier in the wiki I would even allow it for the mounainbike vehicle case also without the "bicycle=yes" tag combination. I would implement this in one step, this probably shouldn't be too difficult.
When we get the possibility to add costs for nodes (#75 ??) , the cost for such a barrier should be quite high, because you definetly have to get off the bike.
Additionally the instructions should eventually tell something like "Get off the bike to pass barrier". But this is another step. After a short glimpse into the code I don't think that this feature is already implemented for other types of barrieres.

**Comment by ratrun** [comment]
I prepared a patch at https://github.com/ratrun/graphhopper/commit/731422eef37cc7b4b30229b3cd20f21f857278f5
which removes the absolute `kissing_gate` barrier for the mountainbike encoder. For other bike encoders this barrier remains absolute.

**Comment by karussell** [comment]
Thanks, looks good! Would you create a PR from this commit?

**Comment by arminus** [comment]
I think the current implementation is too limiting. If there's a tag bicycle=yes on a kissing_gate barrier, it should allow all bike types, not only mountain bikes. Here's an overpass query which shows 34 such barriers in Munich - I seriously doubt one needs an MTB there ;-)

http://overpass-turbo.eu/s/9su

**Comment by karussell** [comment]
(reopened this issue due to this and the discussion on the mailing)

**Comment by ratrun** [comment]
Could you please provide a picture of a kissing_gate which can be passed easily by bike and where you put would set the tag `biclycle=yes`?

Here is the "reference" picture from the OSM wiki: http://wiki.openstreetmap.org/w/images/thumb/7/7b/TL0452_stile.jpg/300px-TL0452_stile.jpg

I doubt that the 34 kissing_gates in Munich are tagged correctly. 

I don't want to be routed via such an obstacle except on a mountainbike tour without having the option to put a big penalty cost on it. You need to get off the bike, at least open a gate and close it again. Most kissing_gates I'm aware of require you to lift the bike to 90 degrees and wheel it on the rear wheel around a very tight 180 degree cage thing.

Those things are a real pain in the ass. I doubt that as a cyclist you would lough as these two ladies do: See http://tinyurl.com/og9zh8z .

**Comment by karussell** [comment]
> I doubt that as a cyclist you would lough as these two ladies do: See http://tinyurl.com/og9zh8z 

lol

**Comment by arminus** [comment]
@ratrun I'll get you some pictures... 

"You need to get off the bike, at least open a gate and close it again." 

right - and somebody during tagging explicitly said that bikes are allowed. So would you rather get rerouted some hundred meters or more around that "obstacle"? personally, even on my race bike, I'd rather briefly jump off the bike and probably stay on a smaller track as a result...

So, IMHO, if someone has explicitly put a tag bicycle=yes on any barrier, there's no rational of blocking this barrier completely during bicycle routing. Even more so since GH hardcodes that (compare to Routino which puts these kind of decisions into a user modifiable XML file). Penalty, fine, but no resulting reroute.

Just my 5 cents...

**Comment by karussell** [comment]
Hmmh, really hard decision. Probably for racing bike it is also allowed, but for normal bike we should not allow it, as for them we have to assume luggage which makes this a real hassle. Of course in a later version we make this configurable (#193)

**Comment by PatrickvEk** [comment]
In the Netherlands aka 'the bicycle country', I found this restriction being too restrictive. I plan cycling trips every week on our national cycling node network. Basically the purple lines on OpenCycleMap. These routes and cycleways are acessible and meant for all types of bicycles. I was a bit shocked to see our beloved GraphHopper routing arround many of the very nice spots these routes take you along.

Example:
https://graphhopper.com/maps/?point=52.084253%2C5.548697&point=52.088275%2C5.557398&locale=en-US&elevation=true&profile=bike&use_miles=false&selected_detail=max_weight&layer=TF%20Cycle

Because of the kissing gate, you cannot reach the old fort. As a software engineer and an OSM mapper myself, I'd love to see a  way to have Graphhopper route over the nice bits like these.
I'm willing to contribute in any way, either by makeing a fix, or customisation in graphhopper itself or finetuning tags in OSM to get this going ;)

Kind regards,
Patrick

**Comment by karussell** [comment]
Yeah. Especially if it is explicitly tagged we should indeed allow it and move those barriers with `kissing_gate` (and maybe also `stile`) to an optional barrier. WDYT @ratrun 

And of course also the current work on customizable routing should be expanded to node tags too.

**Comment by ratrun** [comment]
When I did the research for the kissing_gate 6 years ago I only used https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dkissing_gate as input. From the description there about the small space in the cage I came to the conclustion that such a thing is not designed for bicycles and therefore the `bicycle=yes` are most likely tagging errors. It should be a conventional gate then. I never tought that they would be used for touring cycle routes.

I still believe that these are tagging errors in most cases. @PatrickvEk Do you have a picture of a kissing_gate which you can easily pass with a touring bike loaded with panniers without putting it on the rear wheel? 

On Wikipedia https://en.wikipedia.org/wiki/Kissing_gate they are talking about an additional conventional gate nearby or a latch :
"The gate may be made large enough to fit wheelchairs and the like. Alternatively, to allow pushchairs, wheelchairs, bicycles, and other things too large to pass through, a conventional gate with a less consistent swing-back or default animal-proof mechanism may be nearby, or an additional latch may allow it to open more fully."
If there is a conventional gate besides then this should be mapped that way. I have no idea how common these latches are, but I have nerver met this anywhere.

Regarding the `stile`: Here you only need to lift your bike, without putting in on the rear wheel. Therefore we propably should allow that.

**Comment by PatrickvEk** [comment]
@ratrun  
>> Do you have a picture of a kissing_gate which you can easily pass with a touring bike loaded with panniers without putting it on the rear whe

Yes of course, this a kissing gate i'm using often with the regular bike. You can run it arround in the big round cage without lifting the rear wheel (and luggage). The Diameter of the cage is quite big, meant for regular bikes.
These types of kissing_gate is very common in the netherlands arround the national node networks. I use them very often, if you like I can link you more pictures.

Picture of the situation from the link above:
https://www.mapillary.com/app/?lat=52.084936322263&lng=5.551783739179&z=17&mapStyle=OpenStreetMap&pKey=4216916698373227&x=0.5325726602783849&y=0.6061635107610179&zoom=0


Kind Regards,
Patrick

**Comment by ratrun** [comment]
The picture and taginfo https://taginfo.openstreetmap.org/tags/barrier=kissing_gate#combinations convinced me.

**Comment by PatrickvEk** [comment]
Thank you very much. Good to know about the tag-info helper. Thanks for that as well ;)

**Comment by ratrun** [comment]
This ticket can be closed.
