### ISSUE TITLE
Improve motorcycle profile

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#425]
Include the [bendiness of a road](http://www.technomancy.org/openstreetmap/bendy-roads/) and prefer higher values in the weighting, make it possible to change the influence on the fly (so do not pre-calculate priority)

**Comment by boldtrn** [comment]
Hi Peter @karussell ,

we are currently working on that feature. Right now, we did a quite easy implementation. Created a weighting that knows the curvy roads and returns 0, when weighting a curvy road (we basically have a list of curvy roads).

The biggest issue is, that even when using the Motorcycle flagEncoder, routes that could be done on a highway are routed over that highway. 

Since you understand all the internals, how would you tackle the issue?

I think a good solution would be to add a curvature parameter (the higher the more curvy the road is) to each edge in a preprocessing step (when loading the .pbf). There is a nice python library that does something similar and exports .kml files (https://github.com/adamfranco/curvature).

Afterwards, a weighting like: ```distance / speed*curvature```could be feasible. However, I am still not sure about the highway thing. When riding the motorcycle one wants to avoid highways, as long as there is at least a more or less acceptable alternative.

Best,
Robin

**Comment by karussell** [comment]
Yes, you'll probably need both: mark as highway and increase weighting for that, and mark the 'bendiness' of each edge. Both done for the import so that it is accessible somehow in the weighting (either in the flags or in a separate DataAccess object or similar).

**Comment by boldtrn** [comment]
Hi Peter @karussell ,

thanks for your comment. 

Since, I lack some understanding for the internals of graphhopper could you please explain me these points:
- How to check for the road type in a weighting implementation?
- How do the flags work and how would I create a new flag?
  - I've read your post about the internals. There you describe that each edge consists of parameters. But somehow I am not able to find something that explains how to work with these properties and flags. I've seen the bike2 encoder. You basically add an ```EncodedDoubleValue```. Is this how to add new Flags?
- Where to apply the curvature calculation?
  - I've seen the method `processWay` in the `OSMReader`, is that the correct location?
  - Alternatively is it the `preProcess` in the `OSMReader`

Cheers,
Robin

**Comment by karussell** [comment]
> How to check for the road type in a weighting implementation?

Currently only possible if you add a EncodedValue to the flags on import. But e.g. the motorway should be already avoid. See the avoidSet and method handlePriority. Here we store an EncodedValue ("priority") and is then access in the Weighting via `flagEncoder.getDouble(edgeState.getFlags(), KEY)` see PriorityWeighting

> How do the flags work and how would I create a new flag? 

Currently you can only add information to the 32 or 64bit flags. We'll add very soon more possibilities. Another option is to use a separate DataAccess object, which isn't that hard to implement but not straight forward.

> You basically add an EncodedDoubleValue. Is this how to add new Flags?

Yeah, but I feal your pain. This will be easier, see [here](https://discuss.graphhopper.com/t/more-flexibility-in-gh/71)

> Where to apply the curvature calculation? 

I would do this in the FlagEncoder while import as it is very expensive and yes processWay calls the flagEncoder to do this. preProcess is where nodes are selected for import

**Comment by boldtrn** [comment]
Thanks Peter @karussell ,

> use a separate DataAccess object

So, if I get you right, this means to create another `int[][]` that holds the id of the node and additional parameters for each of these nodes? This object could live in the FlagEncoder and could be accessed in the weighting and the initial import.

Best,
Robin

**Comment by karussell** [comment]
Yes, exactly. I would put the DataAccess in the Weighting but it does not really matter.

> int[][] that holds the id of the node and additional parameters for each of these nodes?

The ID is not necessary to store here, as it is implicitely the index of that array (btw: it is a double array only to avoid 2gb limits and increase size with smaller GC pressure)

**Comment by karussell** [comment]
This is fixed via #534 and we could close here?

**Comment by boldtrn** [comment]
I think so, yes :)
