### ISSUE TITLE
java.lang.AssertionError: endless loop detected during Import

### ISSUE THREAD

**Issue by alienscience** [graphhopper/graphhopper#438]
Hello,
  I am using my own importer, and during import I get the error:

````
Exception in thread "main" java.lang.AssertionError: endless loop detected for 130201, 4407876, 171651584, 5364112
	at com.graphhopper.storage.GraphHopperStorage$EdgeIterable.next(GraphHopperStorage.java:811)
	at com.graphhopper.storage.GraphHopperStorage.edge(GraphHopperStorage.java:338)
```

This error occurs because I am adding data using the EdgeIteratorState and EdgeIterable.next() is checking for loops. Is this checking necessary during import? There will be loops because the complete map is not imported at this stage.

Thanks in advance for your help

**Comment by karussell** [comment]
If you have many edges per node you can get this error. But under normal circumstances for a normal 'geographical graph' and even for the contracted graph you should be fine. And yes, this check is necessary to prevent us from programming mistakes and to make early exits instead of endless loops. If you need more than x edges per node you can just increase the maximum allowed number.

**Comment by Jonnnnn** [comment]
Hi i also have the same problem of endless loop, can i ask how to increase the maximum allowed number of edges?

**Comment by karussell** [comment]
Closing here. Please reopen if we should make this configurable or if you found a bug!
