### ISSUE TITLE
RailWay Routing instead of Car

### ISSUE THREAD

**Issue by sadaqatbukhari** [graphhopper/graphhopper#443]
Hi, I am using GraphHopper Api for routing, I need to know how can I change from car to Railway? Could you please guide me how can I use these option mentioned in OSM http://wiki.openstreetmap.org/wiki/Key:railway using GraphHopper.

Regards,
Sadaqat

**Comment by jansoe** [comment]
Currently the Directions API does not support Public Transport. 
If you want to route along railways (without taking any time-tabling information into account), you can set up your own GraphHopper instance and create a new FlagEncoder (https://github.com/graphhopper/graphhopper/blob/master/docs/core/create-new-flagencoder.md) which encodes the railway network.

Also, for usage questions, please use the [mailing list](https://lists.openstreetmap.org/listinfo/graphhopper) instead of github.
