### ISSUE TITLE
Ferry issue for foot routing

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#501]
Reported [here](https://lists.openstreetmap.org/pipermail/graphhopper/2015-August/002323.html) and works for biking, so it should work for foot too.

That it does not work for car is okayish as ferries are not preferred due to costs and uncertain duration.

**Comment by ratrun** [comment]
The reason for this finding is a wrong implementation of the duration tag. The format hh:mm:ss is currently interpreted as dd:hh:mm . See http://wiki.openstreetmap.org/wiki/Key:duration .

**Comment by karussell** [comment]
Thanks for this finding! Maybe this should be also documented in the OSM wiki?

**Comment by ratrun** [comment]
The wiki already documuments it since 16:18, 29 January 2013. I seems that a `dd:hh:mm` format was never documented. To be precise: the wiki documents a 'hh::mm::ss' format (with double colons). The double colons must be a typo, because the 25 real-world examples I found with overpass query   `way["duration"~"[0-9][0-9]:[0-9][0-9]:[0-9][0-9]"]({{bbox}}) ` in France but no match at all for `way["duration"~"[0-9][0-9]::[0-9][0-9]::[0-9][0-9]"]({{bbox}}) ` world-wide.

**Comment by karussell** [comment]
Do you have a link for future reference?

**Comment by ratrun** [comment]
Probably you meant this link: https://graphhopper.com/maps/?point=47.19415%2C-1.676384&point=47.19747%2C-1.671832&locale=fr-FR&layer=Lyrk

**Comment by karussell** [comment]
Sorry, I meant the OSM docs link but now I can see the 'hh:mm:ss' :)
I thought before you meant 'PT02:25:06' which is not yet supported as it is very inconsistently used in OSM data.
