### ISSUE TITLE
Smoothing of elevation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#517]
Discussed in #209 but should happen on import and GPL code is really a no go and we cannot reuse the core method from this issue - we cannot even look into it.

The smoothing should happen on import e.g. could be here #507

Relates to #384

**Comment by karussell** [comment]
As noted from @ratrun the code was replaced with his own smoothing method - feel free to submit this here as separate issue.

**Comment by ratrun** [comment]
I don't think that it is good idea to generally include my smoothing algorithm, which improved the calculation of the total ascend and the total descend. The reason is that it also changes the value of the start and the end point. This is totally fine for the computation of the total ascend/descend, because thae absolute values are of no importance, but I don't think that it is a good idea to use it in general. The algortihm I used basically comes from here: http://phrogz.net/js/framerate-independent-low-pass-filter.html.  I run it twice: once forward and once backward and then I take the mean average for each single point.

**Comment by boldtrn** [comment]
Maybe it would also make sense to switch the elevation data source? It is possible to switch to 1 arc second data instead of 3 arc seconds, which might improve the data. For example there is the SRTMV3 data that is available in 1 arc second with filled holes. Also there are other sources like http://www.viewfinderpanoramas.org/ which is considered a high quality resource for dems.

Maybe it would make sense to host our own smoothed version of e.g. the SRTMV3 data. AFAIK, the best smoothing can be done with [mdenoise](http://www.cs.cf.ac.uk/meshfiltering/index_files/Page342.htm). The smoothing process is very hardware intensive, smoothing the SRTM data of the whole world, might take weeks, depending on the input parameters of mdenoise. See for example this [paget](http://personalpages.manchester.ac.uk/staff/neil.mitchell/mdenoise/) that shows the impact of iterations. However we have to test if smoothing solves our dem related issues.

**Comment by karussell** [comment]
> Maybe it would also make sense to switch the elevation data source?

This is another issue: #384 and the mentioned link uses stuff where the license is not clear for all areas.

> Maybe it would make sense to host our own smoothed version of e.g. the SRTMV3 data. 

Yes, would love to see this (probably in the other issue) and we could provide processing power (for hosting I'm unsure as this requires other stuff). And then we can see if this helps improving here too.

**Comment by boldtrn** [comment]
> This is another issue: #384

I found that issue after I commented here, sorry :).

> mentioned link uses stuff where the license is not clear for all areas.

Ah, you are right. I forgot about that. 

> However, some of the data was obtained from Soviet topographical maps that is not available for licensing, according to a blog post comment. Please use with caution. -- From https://wiki.openstreetmap.org/wiki/SRTM

> for hosting I'm unsure as this requires other stuff

I could also host these on srtm.kurviger.de. I think the biggest problem here is to setup a workflow that does not run forever, but still provides better results than CGIAR and is repeatable (some sort of automation would be great).

**Comment by boldtrn** [comment]
I am not sure if this belongs here or into a new issue, but I think the reason for the following observations happens because of the missing smoothing.

Currently the ascend and descend are incorrect. Have a look at this route.

[GraphHopper](https://graphhopper.com/maps/?point=48.549058%2C9.385382&point=48.545848%2C9.391165&point=48.534795%2C9.406786&vehicle=bike&weighting=fastest) - ↗598m ↘316m, [Google Maps](https://goo.gl/maps/jVFA5i8fsUB2) - ↗296m ↘14m

I have ridden this road many times, I don't know the exact ascend/descent, but there is not much descent if any (so Google Maps looks more correct to me).

The same is true for this road: [GH](https://graphhopper.com/maps/?point=48.573654%2C9.413567&point=48.560363%2C9.430218&vehicle=bike&weighting=fastest) [GM](https://goo.gl/maps/4KfpBRbmxVT2).

In both cases the overall ascent-descent are pretty much the same, but the actual numbers differ. I am not sure if we actually need to smooth the elevation, but this would probably make the most sense?

**Comment by karussell** [comment]
I think the problem is not the smoothing it is more the precision of the elevation data which means that a cell of the higher areas overlaps the road and causes a big increase, see #384 for the related issue IMO.

**Comment by boldtrn** [comment]
> I think the problem is not the smoothing it is more the precision of the elevation data which means that a cell of the higher areas overlaps the road and causes a big increase, see #384 for the related issue IMO.

But this would be also fixed if we smooth the elevation for every way? For example we could define a maximum steepness per vehicle profile. When calculating the ascend and descend in the PathMerger we could "smooth" the elevation data, which could remove the spikes.

**Comment by karussell** [comment]
There are three problems: gaps in the data (this is the reason we use CGIAR and not SRTM ala 90m), lack of precision (reason we should use SRTM ala 30m but there might be gaps although some sources say they are void filled, see #384) and lack of smoothing. I do not think that smoothing alone solves all issues but will help a lot. Also there is smoothing as a preprocessing step (will improve routing too) and smoothing per response (will be just cosmetic & improves the ascent&descent value but I do not like it much as it will make debugging harder)

**Comment by boldtrn** [comment]
> smoothing per response

Is this included in the current master? I have seen an approach by @ratrun, but I think we didn't merge it into the master, right?

BTW: I also replied in #384 about the high precision data.

**Comment by karussell** [comment]
> > smoothing per response

> Is this included in the current master?

no, see his comment: https://github.com/graphhopper/graphhopper/issues/517#issuecomment-140482083

**Comment by boldtrn** [comment]
I recently had a nice discussion with @dhowden and @tbillington regarding elevation smoothing. In contrast to the calcAverage method we currently use in the `HeightTile` we could try to create a [Bézier surface](https://en.wikipedia.org/wiki/B%C3%A9zier_surface) from the hgt/tiff files. 

The HeightTile would contain a formula (surface formula) that would return the height of a point for a given lat/lon instead of storing the height information for each cell of the grid. 

The implementation is probably not straightforward and probably a solution like #1220 might be easier.

**Comment by boldtrn** [comment]
This should be close with #1220.
