### ISSUE TITLE
Improve location lookup to avoid geocoding mismatch

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#549]
Geocoding is done separately and can have big mismatches where the geocode location snaps to e.g. a closer motorway and not to the intended nearby street of a specific house. Or where a building is directly under or near a bridge etc.

To prevent the users from these mismatches we need to include an address or street hint for the location lookup - we could name this `point_hint` or `address_hint` or similar. Then while lookup we calculate the Levenshtein distance for every point (if cached for one request it should be cheap) and we sort by this distance and filter out bad results. If only 'bad results' no filtering should happen. The question is how much a similarity should influence the snapped distance, i.e. what to do if the street Y looks a bit more similar than X but X is closer.

Furthermore two more improvements are possible
- the 'heading' parameter could be used as a `direction_hint` and improve the routing near a motorway (where one could exclude certain snapped locations based on this hint). 
- we can provide a subnetwork counter in the 'nearest' endpoint and have to include the address hint there too or return a list of matches with different streets etc.

Related to #729

An example can be many buildings on 'the corner' of a junction. E.g. 'Laufamholzstraße 154 Nürnberg' which currently geocodes to [49.46553,11.154669](https://graphhopper.com/maps/?point=49.46553,11.154669) and so it snaps to the closest 'Vorrastraße' but should snap to something like [49.465687,11.154631](https://graphhopper.com/maps/?point=49.465687,11.154631). Now if we specify Laufamholzstraße or even the full address in the routing we should be able to make this happen.

**Comment by boldtrn** [comment]
I am currently looking into this issue. Something I was wondering about is how to design the `point_hint` (I think point hint might be better, since it belongs to the point?). Would we make the behavior of `point_hint` the same as point, meaning, we have a list of hints, exactly the same length as point, where the first hint is meant for the first point, and so on. Or would we only add a point_hint for certain points, e.G. those that were resolved from GeoCoding, whereas we might not want this feature for lat,lon points. Therefore, we might want to have `poin_hint_1` for `point_1`, but don't add `point_hint_0`, because we don't care about `point_0`, for whatever reason.

**Comment by karussell** [comment]
I would keep it simple and assume that the number of 'point_hint' is
identical to the number of 'point' arguments. And if not throw an exception.

**Comment by karussell** [comment]
Hmmh, interesting. Not sure how to handle this properly. We probably
need some heuristic before applying levenshtein e.g. in combination with
the longest common substring:

https://karussell.wordpress.com/2011/04/14/longest-common-substring-algorithm-in-java/
