### ISSUE TITLE
Loading Graph that is a superset of the requested

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#637]
Consider the following situation:

You prepared a CH Graph for car and bicycle. Now you want to run graphhopper only for car. Shouldn't this be possible without preparing the graph again? 

What happens instead is that we get an exception:
```
Caused by: java.lang.IllegalStateException: Encoding does not match
```

This is not really an important issue, but something I've always wondered.

**Comment by karussell** [comment]
I'm not sure what you mean exactly. You mean you changed the chWeightings from `car,bike` to `car` and expect that it should load it without problems?

First of all this is intended and I do not know a use case where this woud make sense to allow this mismatch for the configuration. The more explicitly we are the better IMO. Of course we could determine automatically which profiles and configs are available and load them instead of requiring the same config but this needs a lot work (and there is already an issue open)

A minor other problem is that `car` on a `car`-graph is different to `car` on a `car,bike` graph because in the second case more junctions are created and it coud be slightly slower (not measured it just guessing) and so the intention of loading just `car` cannot be fullfilled.

**Comment by boldtrn** [comment]
@karussell The use-case was actually development only. I was just wondering if it was possible to easily switch configuration files without needing to re-import the graph. So I had the idea that we could check if the configuration is a sub-set of the loaded graph and just load it. Another example could be to switch to flexibleMode and just load the already imported graph.

When thinking about I could even think of a production use-case were we have a load-balancer setup that calls for car routes server1 and for bike routes server2. The import could be done on server3 were server3 calculates CH for car and bike. But I guess this use-case is just stupid and made up ;)

> there is already an issue open

Oh sorry, I did a quick search trough the issues but seems that I haven't found that issue.

I will close this issue for now.

**Comment by karussell** [comment]
I'm still not sure about your use case. But if there is a good reason to do something like this we should at least consider&discuss it :)

> Another example could be to switch to flexibleMode and just load the already imported graph.

But it should be already possible to do the flexibility queries on a CH prepared graph. Or do you mean you want to save RAM or something like discussed here: https://discuss.graphhopper.com/t/can-i-add-more-chs-later-on/365/

> Oh sorry, I did a quick search trough the issues but seems that I haven't found that issue.

Me too, but a longer search did it ;) https://github.com/graphhopper/graphhopper/issues/285

**Comment by boldtrn** [comment]
> But it should be already possible to do the flexibility queries on a CH prepared graph.

Ahh yes, forgot about that PR. This should be possible with passing the flexible mode with the request.

> I'm still not sure about your use case

My current use-case was that I removed one weighting from my config and wanted to restart graphhopper. Now it has to reimport the whole graph. I just thought that this shouldn't be necessary. This has happened to me quite often over the time with different use-cases, but mostly development use-cases. 

> Me too, but a longer search did it ;) #285

You are right #285 matches my point, but is even going further.
