### ISSUE TITLE
Alternative route improvements

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#649]
We've introduced alternative routing via #640 still there are the following open issues:
- [x] make it possible for CH
- [ ] further performance improvements ('Improved Alternative Route Planning' paper), the alternative calculation itself takes only a few percentage of the whole search
- [ ] post processing alternatives to throw away too bad alternatives (e.g. alternatives that are too similar to other alternatives) was necessary in this local query](for final alternative list: remove last alternatives if too much share from previous like necessary [here](http://localhost:8989/?point=49.942825%2C11.576843&point=50.002443%2C11.618557&vehicle=car&alternative_route.max_paths=2&algorithm=alternativeroute) or [here](http://localhost:8989/?point=49.942355%2C11.576908&point=49.482401%2C11.013794&vehicle=car&alternative_route.max_paths=5&algorithm=alternativeroute)
- [ ] can we avoid alternatives with motorways just going back and forth? [local query](http://localhost:8989/?point=48.487486%2C10.118408&point=47.661688%2C10.000305&vehicle=car&alternative.max=3&algorithm=alternativeroute), [query 2](http://localhost:8989/?point=49.942825%2C11.576843&point=50.035753%2C11.681213&vehicle=car&alternative_route.max_paths=3&algorithm=alternativeroute&alternative_route.max_share=0.4)
- [ ] integrate multiple alternatives into GPX with multiple entries -> GPX export in josm works this way
- [ ] test query torture for new log layout (necessary due to refactoring and new log format)
- [ ] why sometimes no alternatives at all? [example](http://localhost:8989/?point=49.942825%2C11.576843&point=50.059563%2C11.67778&vehicle=car&alternative_route.max_paths=5&algorithm=alternativeroute&alternative_route.max_share=0.4)
- [ ] let influence the SPT-counter (see alternative roads to rome post) the selection of a good plateau? e.g. sum of weight_i*count_i for just the plateau (?) but this seems to be too expensive to calculate!

**Comment by boldtrn** [comment]
Good points!

> integrate multiple alternatives into GPX with multiple entries -> GPX export in josm works this way

Do you think it would also make sense to add a parameter like `gpx_export.use_route=ROUTE_NUMBER`? In my experience importing multiple GPX routes does not work as expect, as most navigation devices will just use the first route or try to concat the routes. I think that could be a fast fix for the GPX export.

**Comment by devemux86** [comment]
Indeed provide some flexibility like choose the exported path would be convenient for cases where we need a gpx with only the "active" route in it.

**Comment by karussell** [comment]
How would a client use this API efficiently? (e.g. how the client knows the maximum number of alternatives for this route?)

Wouldn't it be better there was only one request and the client is able to pick the route without further HTTP requests?

**Comment by boldtrn** [comment]
> How would a client use this API efficiently?

Here is how I would use it:
- Calculate a route with alternative_routes
- Select the alternative route that I like (in GraphHopper maps this would be the tab chooser)
- When exporting I would get the selected path

> (e.g. how the client knows the maximum number of alternatives for this route?)

My assumption in this case is that one calculates the route beforehand. This allows the client to know how many paths there are.

> Wouldn't it be better there was only one request and the client is able to pick the route without further HTTP requests?

Depends on the use-case IMHO. I thought about the use-case of  navigation. Calculate a route with GH, export GPX, import the GPX into a navigation device/service.

From my experience importing multiple GPX tracks/routes into navigation devices leads to unexpected results. Also, since not every navigation device supports .gpx a user might need to convert it to a different format. Most other formats don't support multiple tracks. Therefore, it makes sense for me to only export a single path.

On the other hand, when wanting to visualize a gpx file, it might be nice to have the alternative routes.

**Comment by devemux86** [comment]
>My assumption in this case is that one calculates the route beforehand. This allows the client to know how many paths there are.

Indeed clients usually have calculated the route(s), visualize them and then provide the user an option for export.

>So I think in the future we should allow to export multiple paths at once, but still allow to export only a single path.

:+1:

**Comment by easbar** [comment]
Is there a specific reason why alternative routes are not supported for via-routing? I do not really see a reason why we even make a distinction (`Alternative/ViaRoutingTemplate`) in the code. Via routing is just a series of point to point routes and alternative via routing would be the same except there are alternatives for each leg of the trip. Things like `pass_through` or the path merging might need some special handling but otherwise there shouldn't be a real problem? 

The reason I am asking is that I think the whole routing-template/routing-algo-factory approach needs an overhaul :)

**Comment by boldtrn** [comment]
I am with you on this @easbar. I think we had a quite long discussion about this here: https://github.com/graphhopper/graphhopper/issues/771

**Comment by easbar** [comment]
Oh nice I did not see this, thanks a lot for the pointer.

**Comment by karussell** [comment]
We need to open more concrete issues
