### ISSUE TITLE
How to fix NoClassDefFoundError in Eclipse

### ISSUE THREAD

**Issue by gerbsen** [graphhopper/graphhopper#669]
Hey,
I just imported graphhopper into Eclipse. I stumbled over the NoClassDefFoundError which is described in your [documentation](https://github.com/graphhopper/graphhopper/blob/master/docs/core/eclipse-tomcat-setup.md#6-configuring-classpath-and-resolving-maven-dependencies-problem). The workaround you propose seems to be a pain and so I tried to solve this differently and the article [here](http://stackoverflow.com/questions/12931750/maven-dependencies-not-deployed-on-eclipse-tomcat-instance) lead me to this error: "Invalid classpath publish export Project entries not supported" which in turn can be solved via this [method](http://stackoverflow.com/a/6828918/653410). I have absolutely no idea why we need to manually add the deps from the child/other project to the deployment assembly and I have never had to do this myself. Attached you can find an image of my deployment assembly for the graphhopper-web project. Hope this helps. 

Daniel

![screenshot 2016-02-23 11 33 41](https://cloud.githubusercontent.com/assets/1186245/13249087/791dfcf6-da22-11e5-8103-a2edd227786e.png)

**Comment by karussell** [comment]
I have no Eclipse experience myself, but I think instead of manually managing the dependencies - a maven plugin should do this? The documentation, as I understand this, was just to use a different web server and not the in-built jetty, where it should be just a matter of opening the pom.xml and starting the main class (GHServer)

**Comment by karussell** [comment]
If this proposed screenshot enhances the existing documentation - would you mind to create a pull request?

**Comment by boldtrn** [comment]
@gerbsen Haven't tested Graphhopper with Eclipse. But I think it should work using the m2e plugin. Import it as maven project (which is important, so eclipse can build it according to the pom). You have to setup the parameters for running Graphopper. This was described [here](https://discuss.graphhopper.com/t/start-ghserver-from-intellij-message-not-found/347) and [here](https://discuss.graphhopper.com/t/how-to-develop-or-change-stuff-in-graphhopper-and-use-ide-features-like-debugging-etc/154).

**Comment by mcrnotts** [comment]
If you are looking to update the documentation regarding adding the dependencies back into Classpath then I also recommend a quick skim of my answer to my own question here http://stackoverflow.com/questions/31167358/adding-maven-dependencies-back-into-graphhoppers-classpath-causes-a-working-tom 

Following the existing documentation:
"Take a look at all “.jar files". Be ready to find all these .jar files in your system, and to make a copy of them in a folder."

"You have to add all these files to “Classpath” as well. On Project explorer, right click on graphhopper-web [graphhopper master] and go to “Run As” --> “Run configuration…” then choose “Classpass” tab. Under “User Entries” , you see only a few “.jar files”. It should look like the below figure."

The problem is that adding **all** of the dependencies in this list simply would not work for errors unknown to me. By an approach of adding one-by-one in response to the NoClassDef error, I was finally able to reduce the list needed to be added back into class path to make it functional. Less .jar to track down, and potentially a headache avoided :)

**Comment by karussell** [comment]
I wonder why this is all so complex in Eclipse. If you are using the maven plugin then it should be a lot simpler IMO, in NetBeans and IntelliJ you can just click on any project with a pom.xml and all works.

**Comment by devemux86** [comment]
FYI recently I tried again GraphHopper in Eclipse (with Maven) and it was indeed as simple as importing its Maven project.

**Comment by gerbsen** [comment]
Have you tried to start the (tomcat) server in eclipse? I've lots of other projects which work as expected. My guess would be that the module configuration is not correct, but I probably don't have the time to debug this.

**Comment by devemux86** [comment]
Sorry I didn't tried that exact step, more occupied with other GH parts.

**Comment by karussell** [comment]
Can we close here?
