### ISSUE TITLE
Force side of the street

### ISSUE THREAD

**Issue by ov3gwifi** [graphhopper/graphhopper#680]
Implement a new feature to support right side pick-up.

**Comment by karussell** [comment]
Isn't this already possible with our `heading` #434 or what exactly are your requirements?

**Comment by ov3gwifi** [comment]
Any Answer ????

**Comment by karussell** [comment]
> i'm talking about final destination enforcing. 

The direction of the final destination can be already enforced via the `heading` parameter - see here: https://github.com/graphhopper/graphhopper/blob/master/docs/core/routing.md#heading

You'll need to enable the flexibilty mode (prepare.chWeighting=no) or see #631 

> Any Answer ????

Please do not trigger issues via meaningless comments.

So, in summary what you want is to specify "right side destination"  instead of the heading parameter. A simple workaround for now is to calculate the heading based on the snapped point and enforce this. A more precise solution would take account of "right side destination" already when searching for a nearby road, since if one way roads are involved this could be different to the nearby street without that constraint.
