### ISSUE TITLE
Android Device Draging and Scrolling Crash with Crash Report Dump

### ISSUE THREAD

**Issue by chathura1** [graphhopper/graphhopper#692]
On Android actual device running 5.1.1, scrolling map will cause app to crash.  However, onLongPress works with routing as expected. I also noticed on AVD API 23 it scrolling works fine. Also pressing zoom out causes app to crash on the device.

Attached is the library crash report.
[http://appsforfree.org/apk/tombstone_00](http://appsforfree.org/apk/tombstone_00)

using following tutorial on how to decode the crash dump into actual library failes.
[http://www.lindusembedded.com/blog/2011/08/04/debugging-android-core-dumps/](http://www.lindusembedded.com/blog/2011/08/04/debugging-android-core-dumps/)

I am not sure which .so file graphhoper is using so I can decode the crash dump into actual .cpp files that caused the failure.

**Comment by devemux86** [comment]
GraphHopper uses [Mapsforge](https://github.com/mapsforge/mapsforge) library for the offline vector map rendering (both do not use NDK i.e. .so files).

This issue is probably map related (and not routing), so you could post additional information there (e.g. device model).
(see [here](https://github.com/mapsforge/mapsforge/issues/789) for an opened issue)
