### ISSUE TITLE
Move map matching modules into this repository?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#792]
In #781 I stumbled over the necessity to add map matching as dependency. But we would either have to move the `reader-overlay-data`-module into the map matching repository or move the map matching into this repository to avoid cyclic dependencies. Or some kind of plugin architecture has to be developed for the web module. Not sure.

No maven dependencies will be changed due to this, just handling the sources, deployment, setup and compilation together. 

Also in case we move the mapmatching to this here, we would need to merge both start scripts somehow and source code history would be lost, as well as all the stars.

It would simplify deployment and release management as we do not need do duplicate everything for both repositories.

**Comment by devemux86** [comment]
I suppose git [submodules](https://git-scm.com/book/en/Git-Tools-Submodules) cannot help here?

**Comment by karussell** [comment]
They could but we should really not use them, as they seem simple at first but makes everything unnecessarily complex.

**Comment by devemux86** [comment]
Modules depending on GraphHopper core and being closely related to its routing could be hosted under same project, retaining their integrity. Additional benefit is that they'll advance in parallel with it.
:+1:

**Comment by kodonnell** [comment]
I'm in favour of merging, as they solve similar problems. For example, GH currently lets you provide a set of waypoints to route, and then routes between each of them to get a final route. In most cases, I suspect people may have actually been intending to use map-matching. (I know that this was the case for us at work.)

I also suspect that having the two in the same repository (and API?) will result in more unified/tidy code and a better experience for users.

**Comment by karussell** [comment]
> I also suspect that having the two in the same repository (and API?) will result in more unified/tidy code and a better experience for users

I do not intend to merge the core modules, maybe merge the web modules, not sure. So I would as a first step just move the modules into the same repository so the code and dependencies will be unchanged. The start script will unified though.

**Comment by stefanholder** [comment]
>source code history would be lost

There are several approaches to retain the source code history of the map-matching repository: http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

The soution suggested in answer 3 using `git merge --allow-unrelated-histories` seems most promising to mee.

**Comment by karussell** [comment]
Sounds good @stefanholder. 

And as we could then simplify the 'tools' to include the measurement and a debug UI for both projects, this issue would make a lot of sense. Furthermore we could take the chance and strip some of the osm files in the map matching repo, or at least move the `core/files` into the root folder and copy the files from the MM/map-data there.

**Comment by kodonnell** [comment]
@karussell are you the best person for doing this? I could try, but this sort of git stuff scares me somewhat! Maybe we could start by just bringing map-matching in, and start merging the functionality as separate PRs?

**Comment by kodonnell** [comment]
> a debug UI for both projects

An indirect benefit from this - if we have one UI for both, then we can make it clear to users that they have both options (GH waypoint routing or map-matching), and they can choose which is most appropriate by comparing the results from the GUI. I suspect most people with multiple waypoints do not appreciate why they need map-matching, and think naive waypoint-to-waypoint routing should work. In fact, I can't see many cases where you'd want to use waypoint routing instead of map-matching ... I'd suggest map-matching should replace it, both in functionality and the API. So we treat map-matching as just a different routing algorithm (I suspect we can refactor so that we can just use e.g. `mapMatchingAlgo.calcPath` etc).

One could easily see it extending to the final web apps too. E.g. if you input more than two waypoints, it asks whether you want to use map-matching (or defaults to it).

The reason I mention it is that I know of some people who just delivered bogus results to a client due to effectively using GH to route a GPX track point-to-point without using map-matching. (That said, I actually warned them of this, so maybe they wouldn't have learned anyway!)

**Comment by karussell** [comment]
For now we keep the repositories separate. The arguments are better visibility but also the issues can stay.
