### ISSUE TITLE
Merge Helper and Helper7?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#853]
See [comment](https://github.com/graphhopper/graphhopper/pull/852#issuecomment-257015126)

**Comment by karussell** [comment]
@devemux86 do you know if Helper7.java would make problems when copied to Helper.java under Android?

**Comment by devemux86** [comment]
`Helper7` uses JDK specific classes that don't / won't exist on Android.
`7` could be a bit misleading, name could change to something more related to Desktop / Web?

**Comment by karussell** [comment]
Currently not worth the effort. Still hope that Google does something about this ugly difference ...

**Comment by carlos-mg89** [comment]
Hi, just found that you talked about Helper7 here, because Lint is pointing me out 2 invalid package references:

> ../../../../../.gradle/caches/modules-2/files-2.1/com.graphhopper/graphhopper-core/0.10.3/463cc79b54476634ff5d164cbedf1657976b698c/graphhopper-core-0.10.3.jar: Invalid package reference in library; not included in Android: java.lang.management. Referenced from com.graphhopper.util.Helper7.

and

> ../../../../../.gradle/caches/modules-2/files-2.1/com.graphhopper/graphhopper-core/0.10.3/463cc79b54476634ff5d164cbedf1657976b698c/graphhopper-core-0.10.3.jar: Invalid package reference in library; not included in Android: javax.xml.stream. Referenced from com.graphhopper.util.Helper7.

Does anybody know how could this be fixed?

Thanks in advance!

**Comment by devemux86** [comment]
`Helper7` was not meant for Android? So should be safe to ignore / disable these warnings.

**Comment by carlos-mg89** [comment]
@devemux86 this is what I have ended up doing. I marked the Graphhopper JAR as an invalid package for Lint, and then it passed the Lint check:

```
<lint>
    <issue id="InvalidPackage">
        <ignore path="**/graphhopper-core-0.10.3.jar"/>
    </issue>
</lint>
```

However, I have the feeling this isn't right. Or at least, not as right as it should be. In theory, what I've been reading about this, is that this happens when a library / package is not using Android classes. 

Thanks anyway for pointing out it should be safe to ignore this. It wasn't a warning by the way, it was an error from Lint. It doesn't happen when you normally build the APK though.
