### ISSUE TITLE
Web interface: make static links with OSM IDs or some other unique reference, not the names shown in input fields

### ISSUE THREAD

**Issue by sebalis** [graphhopper/graphhopper#889]
As we know, when researching a route by entering a (partial) place name rather than coordinates, there can be more than one match in the OSM data and the Graphhopper web GUI will then offer a list of matches for the user to click on. But sometimes several of these matches lead to the same display string in the input field once they are chosen by the user. When a static link is then generated, this display string is included in the request parameters. When that static link is later opened, Graphhopper has to choose from these multiple matches, and it can of course make a different choice to the one originally made by the user. That can make it impossible to produce static links to routes that have human-readable points. Suggestion: continue accepting static links with such named parameters, but in the future generate (and interpret) links with values such as _**type**_/_**x**_, where _**type**_ is _node_ or _way_ – I assume those are the only types of OSM objects that can be chosen – and _**x**_ is the ID of the chosen object.

**Comment by boldtrn** [comment]
I had this issue as well in the past. However, the OSM ID is not static. Generating only links with lat lon, is convenient for developers, but having `p=Berlin` is nice for the user. Also this issue seems to happen very infrequently, so it might not justify the change. However it might be a good idea to improve the name generation from the GeoCoding. Currently when you go to `p=Berlin`, GH requests a GeoCoding service to get the lat,lon for that name. If we can generate more unique names here this would improve the matching.

**Comment by boldtrn** [comment]
BTW: Here is a nice [example](https://graphhopper.com/maps/?point=Mae%20Hong%20Son%2C%20Thailand&point=Back%20Trax%20Tour%2C%2058130%2C%20Pai%2C%20Thailand). As you can see, the first point is not found. If you use the forward geocoding, it places the point correctly on the street, the reverse geocoding places the point 10-20km away.
