### ISSUE TITLE
encoded value: rounding leads to max value violation

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#947]
[This code](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/util/EncodedDoubleValue.java#L56) in EncodedDoubleValue is ugly and we should probably avoid the first 'rounding'. Also it works differently than in EncodedValue.

This leads to an exception when with a precision of 4 the 110km/h is rounded upwards to 112 and violates the maximum allowed value:

```java
   public void testMaxSpeed2() {
       CarFlagEncoder limitedCar = new CarFlagEncoder(5, 4, 0) {
           {
               maxPossibleSpeed = 110;
           }
       };
       EncodingManager em = new EncodingManager(limitedCar);
       ReaderWay way = new ReaderWay(1);
       way.setTag("highway", "motorway");
       way.setTag("maxspeed", "none");
       long flags = limitedCar.handleWayTags(way, 1, 0);
       assertEquals(110, limitedCar.getSpeed(flags), 0.01);
   }
```

**Comment by boldtrn** [comment]
I looked a bit into this issue. So if we avoid the first rounding and would cast the result like `long tmpValue = (long) (value / factor);` we would always round down (drop the decimals). Which would probably lead to incorrect results sometimes.

One example would be this test:
```
public void testSetDoubleValue() {
        EncodedDoubleValue instance = new EncodedDoubleValue("test", 6, 10, 0.01, 5, 10);
        assertEquals(10.12, instance.getDoubleValue(instance.setDoubleValue(0, 10.12)), 1e-4);
    }
```

This would lead to 10.11, instead of 10.12.

So it seems like the issue is created since 110/4 is  27.5 (not a whole number). So would it make sense to require that maxValue/factor results in an integer?

We would limit the EncodedDoubleValue, but I think this would be a "clean" solution.

**Comment by karussell** [comment]
> So would it make sense to require that maxValue/factor results in an integer?

That is a good idea, yes.

What are we doing with the fact that EncodedValue does it differently than EncodedDoubleValue? Should we additionally change the rounding stuff in one of them to have identical behaviour?

**Comment by boldtrn** [comment]
> What are we doing with the fact that EncodedValue does it differently than EncodedDoubleValue?

I think the first rounding is needed to keep the results as good as possible. The second round could be avoided. When retrieving the double value we don't round either, so we should check the value unrounded. Or did I miss anything?

**Comment by karussell** [comment]
> I think the first rounding is needed to keep the results as good as possible. The second round could be avoided

The second rounding is just for the check method and I could live with this difference but I meant:

```java
// EncodedDoubleValue
long tmpValue = Math.round(value / factor);
// vs. EncodedValue
value /= factor; // this is equal to: value = (long)(value / factor);
```

> When retrieving the double value we don't round either, so we should check the value unrounded

What do you mean here?

**Comment by boldtrn** [comment]
Yes, so I played around with removing the Math.round. The problem is, that we would always round down, which IMHO make the result of the EncodedDoubleValue worse. When using a precision of 10 and saving 9, the EncodedDoubleValue will store 0, as 9/10 => 0 without rouding. So with rounding it would store 10.

> What do you mean here?

When we call getDoubleValue, we do `return flags * factor;`, when checking the value we do `checkValue(Math.round(tmpValue * factor));` which seems wrong. We should check the same value we are returning.

**Comment by karussell** [comment]
Ok, so lets change

 * checkValue to a call without Math.round
 * require that maxValue/factor results in an integer

And should we use

long tmpValue = Math.round(value / factor);

also for EncodedValue?

**Comment by boldtrn** [comment]
> long tmpValue = Math.round(value / factor);

I think yes, would be probably better. But this could break/change existing implementations. 

Assuming someone uses an implementation of EncodedDoubleValue with maxValue/factor != integer, they would get an exception and could fix it. If we add a rounding here we might change EdgeFlags without noticing. Probably we should at least add it to the changelog?

WDYT? Should we change it?

**Comment by karussell** [comment]
I would favor that we still do this (in a separate PR) and increase the versions of every encoder that uses this and of course also note this in the changelog

**Comment by boldtrn** [comment]
Should we leave this open until the other issue discussed here is fixed?

> long tmpValue = Math.round(value / factor);
also for EncodedValue?
