### ISSUE TITLE
Make Blocking Edges/Areas pluggable like TurnWeighting

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper#958]
Blocking Edges/Areas is currently only possible with the GenericWeighting. It should be possible to extract that behavior into a pluggable weighting, like the TurnWeighting. This could be used for non ch requests for fastest or shortest weighting.

Implementing this should be straight forward. Move the blocking code from the GenericWeighting into a new class. It might be a good idea to extend the `AbstractAdjustedWeighting`.

**Comment by asdzxcasd** [comment]
I want to get started with graphhopper development, so I'm going to implement this improvement.

I've implemented class `BlockedWeighting` that extends `AbstractAdjustedWeighting`, but I'm doubting about its name. Doesn't "forbidden" have more precise meaning than "blocked", so that the class is named `ForbiddenWeighting`?

**Comment by boldtrn** [comment]
Hi @asdzxcasd, I am happy to hear that you picked up this issue :). I think blocked is a better match than forbidden. For example a road is blocked by an traffic accident or a road is blocked by flooding.

**Comment by karussell** [comment]
Fixed via #1078
